### ISSUE TITLE
Exception when non-existent snapshot image specified in instance create

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#1032]
```
debian@ci-primary:~/andy/kolla-automation$ sf-client artifact list
+--------------------------------------+----------+--------------------------------------------------------+----------+---------+
|                 uuid                 |   type   |                       source url                       | versions |  state  |
+--------------------------------------+----------+--------------------------------------------------------+----------+---------+
| 05410875-b138-4e4a-b724-4f3fdceda7cd |  label   |             sf://label/system/other-and-3              |    1     | created |
| 29c4a657-32a8-40e0-9538-3d9af0c45ae1 |  image   |     sf://blob/995dd09b-47e2-447e-b5b2-353b06991118     |    1     | created |
| 853b0801-7db3-4e62-9b6c-519f5c898ef1 |  image   |    http://139.99.148.197/images/centos-7-base.qcow2    |    1     | created |
| 8b917fbe-a4fd-4e30-914e-64518770f77c | snapshot | sf://instance/1d9d8b73-69b7-42d4-a6b6-34ba0d3e98c9/vda |    3     | created |
| ab3a96a8-f1ea-4762-acdf-f58c968118d6 |  image   |             sf://label/system/other-and-3              |    0     | initial |
| bfbc1d3d-f093-41bc-82e8-e839b42ddd49 |  image   |                                                        |    0     | initial |
| e88e5cb9-c11c-42d0-9cf4-dab6e2c2690d |  image   |  http://139.99.148.197/images/centos-7-desktop.qcow2   |    1     | created |
| ecccf8dc-dcb8-41c4-b306-b22617c53d45 |  image   |     sf://blob/8b917fbe-a4fd-4e30-914e-64518770f77c     |    0     | initial |
+--------------------------------------+----------+--------------------------------------------------------+----------+---------+
```
```
sf-client instance create test3 2 2048 -d 100@sf://snapshot/c1f2cfdf-5a78-4035-b7a8-14cdc351d03a -f 157ebc16-1bd1-49da-a8cf-d08e521622d9 -n 433d21a0-1e9f-47d4-9f95-1f2c68932980
```

```
Oct  5 03:46:54 ci-3 ERROR gunicorn: worker [sf-api][26158] Server error
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/external_api/base.py", line 284, in wrapper
    return func(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/external_api/instance.py", line 134, in post
    blob_uuid = a.most_recent_index.get('blob_uuid')
AttributeError: 'NoneType' object has no attribute 'most_recent_index'
```

**Comment by mandoonandy** [comment]
Closed by #1013
