### ISSUE TITLE
Error while snapshotting in CI

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1090]
```
Oct 31 17:47:38 sf-1 INFO gunicorn: worker [sf-api][3210606] API request parsed; args=(); identity=(None, None); kwargs={'instance_uuid': '38db027d-f77c-4336-929f-b159097894aa'}; method=GET; request-id=64
1f689f-6523-4bfc-8bf3-82aa39047908; url=http://192.168.1.51:13000/instances/38db027d-f77c-4336-929f-b159097894aa/snapshot
Oct 31 17:47:38 sf-1 INFO gunicorn: worker [sf-api][3210606] Yielding index {'blob_uuid': '5557f5bd-074b-49c5-b431-352bff120316', 'index': 1}; artifact=b1773d40-b8bc-40c3-a846-09cb4120d0ed; request-id=641f689f-6523-4bfc-8bf3-82aa39047908
Oct 31 17:47:36 sf-1 ERROR gunicorn: worker [sf-api][3210606] Server error
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 305, in wrapper
    return func(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/artifact.py", line 100, in get
    retval.append(a.external_view())
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/artifact.py", line 201, in external_view
    'size': b.size,
AttributeError: 'NoneType' object has no attribute 'size'
Oct 31 17:47:36 sf-1 INFO gunicorn: worker [sf-api][3210606] Returning API error: 500, server error: AttributeError("'NoneType' object has no attribute 'size'") (traceback suppressed by caller)
```

**Comment by mikalstill** [comment]
This is resolved now.
