### ISSUE TITLE
Error while deleting half created instance

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1095]
```
Nov  1 15:14:06 sf-2 ERROR sf-queues-1635740045.9654691-kelGbGr6XwXmmBjc[2879375] [Exception] Ignored error in sf-queues: 'NoneType' object has no attribute 'network_uuid'
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 116, in handle
    instance_delete(inst)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 362, in instance_delete
    if ni.network_uuid not in host_networks:
AttributeError: 'NoneType' object has no attribute 'network_uuid'
```

**Comment by mikalstill** [comment]
Just saw this one again.
