### ISSUE TITLE
Error creating instance

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1096]
```
Nov  2 11:07:01 sf-2 ERROR sf-queues-1635811616.4654198-4eqjToav750MAaEq[3000162] [Exception] Ignored error in sf-queues: stat: path should be string, bytes, os.PathLike or integer, not NoneTy
pe
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 111, in handle
    instance_start(inst, task.network())
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 314, in instance_start
    inst.create(iface_uuids, lock=lock)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 444, in create
    self._configure_block_devices(lock)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 634, in _configure_block_devices
    util_image.create_cow([lock], cached_image_path,
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/util/image.py", line 65, in create_cow
    info = identify(cache_file)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/util/image.py", line 22, in identify
    if not os.path.exists(path):
  File "/usr/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Nov  2 11:07:01 sf-2 INFO sf-queues-1635811616.4654198-4eqjToav750MAaEq[3000162] enqueue_instance_error; error=Failed queue task: stat: path should be string, bytes, os.PathLike or integer, not NoneType; instance=577d3a0a-54ca-4ff5-a62b-df0e9db836cc
```

This seems to be a race with the new image cache cleaner, where:

```
cached_image_path = util_general.file_permutation_exists(
                            os.path.join(config.STORAGE_PATH,
                                         'image_cache', disk['blob_uuid']),
                            ['iso', 'qcow2'])
```

Returns None indicating the file is no longer in the image cache and we don't check for that (and also shouldn't be deleting things from the cache that we're about to use).

**Comment by mikalstill** [comment]
I think this is resolved now.
