### ISSUE TITLE
Artifact Events Endpoint 

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#1283]
Missing decorator

```
Mar  6 16:32:06 sf-primary INFO gunicorn: worker [sf-api][1212] API request parsed; args=(); headers=Bearer *****; identity=['system', 'deploy']; kwargs={'artifact_uuid': '3040d0bb-165f-417c-9fd5-4056af571b16'}; method=GET; path=/artifacts/3040d0bb-165f-417c-9fd5-4056af571b16/events; request-id=6a8ec4f3-d186-4a67-8b6f-3cd9fb30499c; url=http://192.168.72.200:13000/artifacts/3040d0bb-165f-417c-9fd5-4056af571b16/events
Mar  6 16:32:06 sf-primary INFO gunicorn: worker [sf-api][1212] Fetching system auth token from http://:13000/auth
Mar  6 16:32:06 sf-primary ERROR gunicorn: worker [sf-api][1212] Server error
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 381, in wrapper
    return func(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/artifact.py", line 39, in wrapper
    return func(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 414, in wrapper
    admin_token = util_general.get_api_token(
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/util/general.py", line 74, in get_api_token
    r = requests.request('POST', auth_url,
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 393, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http://:13000/auth': No host supplied
Mar  6 16:32:06 sf-primary INFO gunicorn: worker [sf-api][1212] Returning API error: 500, server error: InvalidURL("Invalid URL 'http://:13000/auth': No host supplied") (traceback suppressed by caller)
```

**Comment by mandoonandy** [comment]
Actually may not be a missing decorator...

**Comment by mikalstill** [comment]
Fixed. The artifact events endpoint now calls `object_events_response()` directly (`shakenfist/external_api/artifact.py:565-583`) instead of building an empty-host auth URL, so the `Invalid URL http://:13000/auth` 500 is gone.

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
