### ISSUE TITLE
While launching many VMs on lots of networks, I got this error

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#131]
While launching many VMs on lots of networks, I got this error. Its weird because I only got it once out of hundreds of networks. A less used code path perhaps?

```
++ sf-client --simple network create 192.168.0.0/24 cybertaipan-20
++ grep uuid:
++ cut -f 2 -d :
Traceback (most recent call last):
  File "/usr/local/bin/sf-client", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/main.py", line 373, in network_create
    netblock, dhcp, nat, name, namespace))
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/apiclient.py", line 275, in allocate_network
    'namespace': namespace
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/apiclient.py", line 140, in _request_url
    return self._actual_request_url(method, url, data=data)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/apiclient.py", line 119, in _actual_request_url
    'API request failed', method, url, r.status_code, r.text)
shakenfist.client.apiclient.APIException: ('API request failed', 'POST', 'http://localhost:13000/networks', 500, '{"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\\", line 104, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\\", line 108, in wrapper\\n    return fn(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\\", line 1074, in post\\n    n.create()\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/net.py\\", line 172, in create\\n    self.deploy_nat()\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/net.py\\", line 198, in deploy_nat\\n    self.persist_floating_gateway()\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/net.py\\", line 97, in persist_floating_gateway\\n    db.persist_floating_gateway(self.uuid, self.floating_gateway)\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/db.py\\", line 165, in persist_floating_gateway\\n    etcd.put(\'network\', None, network_uuid, n)\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/etcd.py\\", line 56, in put\\n    encoded = json.dumps(data, indent=4, sort_keys=True)\\n  File \\"/usr/lib/python3.6/json/__init__.py\\", line 238, in dumps\\n    **kw).encode(obj)\\n  File \\"/usr/lib/python3.6/json/encoder.py\\", line 201, in encode\\n    chunks = list(chunks)\\n  File \\"/usr/lib/python3.6/json/encoder.py\\", line 430, in _iterencode\\n    yield from _iterencode_dict(o, _current_indent_level)\\n  File \\"/usr/lib/python3.6/json/encoder.py\\", line 404, in _iterencode_dict\\n    yield from chunks\\n  File \\"/usr/lib/python3.6/json/encoder.py\\", line 437, in _iterencode\\n    o = _default(o)\\n  File \\"/usr/lib/python3.6/json/encoder.py\\", line 180, in default\\n    o.__class__.__name__)\\nTypeError: Object of type \'IPv4Address\' is not JSON serializable\\n"}')
```

**Comment by mikalstill** [comment]
The floating network had 124 addresses allocated, which probably means it ran through the "heavily used" code path in get_random_free_address():

```
    def get_random_free_address(self):
        if self.in_use_counter / self.num_addresses < 0.5:
            while True:
                addr = self.get_random_address()
                free = self.reserve_if_free(addr)
                if free:
                    return addr

        else:
            idx = 1
            while True:
                addr = self.get_address_at_index(idx)
                free = self.reserve_if_free(addr)
                if free:
                    return addr

                idx += 1
```

**Comment by mikalstill** [comment]
There's another bug here. If _all_ addresses in the netblock are used, we end up in a hard loop I suspect.
