### ISSUE TITLE
If you delete an instance while a snapshot is running, we log a traceback on snapshot completion

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1460]
From CI:

```
Oct  9 00:38:14 sf-5 INFO sf-queues-1665275894.6409912-MuV7aEbCNoaH4BNU[7001] Added event; duration=None; 
fqdn=sf-5; instance=eb6271f4-a444-43af-952b-425c09b67f3d; message=None; operation=queued; phase=delete
...
Oct  9 00:38:15 sf-5 ERROR sf-queues-1665275884.6524768-hsyaOOR91mcrnLw5[6899] [Exception] Ignored error in 
queue worker: 
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/queues.py", line 127, in handle
    snapshot(inst, task.disk(),
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/queues.py", line 419, in snapshot
    b.ref_count_inc()
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/blob.py", line 184, in ref_count_inc
    raise BlobDeleted
shakenfist.exceptions.BlobDeleted
Oct  9 00:38:15 sf-5 INFO sf-queues-1665275884.6524768-hsyaOOR91mcrnLw5[6899] enqueue_instance_error; 
error=Failed queue task: ; instance=eb6271f4-a444-43af-952b-425c09b67f3d
```

**Comment by mikalstill** [comment]
We should just delete the snapshot if the instance was deleted before it completes, its clear the user rage quit at that point.
