### ISSUE TITLE
Missing IPManager when clearing stray networkinterfaces

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1465]
This happens occassionally on the CI cluster:

```
Oct  9 11:40:50 sf-3 sh[3633744]: Process sf-queues-stray-nics:
Oct  9 11:40:50 sf-3 sh[3633744]: Traceback (most recent call last):
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
Oct  9 11:40:50 sf-3 sh[3633744]:     self.run()
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
Oct  9 11:40:50 sf-3 sh[3633744]:     self._target(*self._args, **self._kwargs)
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/net.py", line 40, in _remove_stray_interfaces
Oct  9 11:40:50 sf-3 sh[3633744]:     for n in network.Networks([baseobject.active_states_filter]):
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/network.py", line 779, in __iter__
Oct  9 11:40:50 sf-3 sh[3633744]:     out = self.apply_filters(Network(n))
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/network.py", line 69, in __init__
Oct  9 11:40:50 sf-3 sh[3633744]:     ipm = IPManager.from_db(self.uuid)
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/ipmanager.py", line 59, in from_db
Oct  9 11:40:50 sf-3 sh[3633744]:     db_data = db.get_ipmanager(uuid)
Oct  9 11:40:50 sf-3 sh[3633744]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/db.py", line 46, in get_ipmanager
Oct  9 11:40:50 sf-3 sh[3633744]:     raise Exception('IP Manager not found for network %s' % network_uuid)
Oct  9 11:40:50 sf-3 sh[3633744]: Exception: IP Manager not found for network 90cf3b1e-97b3-48dc-a253-fc6e95afe503
```

**Comment by mikalstill** [comment]
Fixed by 17432c0768cfee82567ac16518187885513310c1 (and not hopefully just masking a problem).
