### ISSUE TITLE
cleaner crash

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#152]
From journalctl on syd-sf-1:

```
Jul 10 10:02:40 sau-cca68-or sf cleaner[23617]: Hard deleting network interface 4274b268-4b93-4820-91aa-fce4a4048a8a
Jul 12 07:35:04 sau-cca68-or sh[23573]: Traceback (most recent call last):
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Jul 12 07:35:04 sau-cca68-or sh[23573]:     sys.exit(main())
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 126, in main
Jul 12 07:35:04 sau-cca68-or sh[23573]:     cleaner_daemon.monitor().run()
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/cleaner.py", line 50, in run
Jul 12 07:35:04 sau-cca68-or sh[23573]:     c.compact(kv.mod_revision, physical=True)
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/etcd3/client.py", line 48, in handler
Jul 12 07:35:04 sau-cca68-or sh[23573]:     _translate_exception(exc)
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/etcd3/client.py", line 46, in handler
Jul 12 07:35:04 sau-cca68-or sh[23573]:     return f(*args, **kwargs)
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/etcd3/client.py", line 1038, in compact
Jul 12 07:35:04 sau-cca68-or sh[23573]:     metadata=self.metadata
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 826, in __call__
Jul 12 07:35:04 sau-cca68-or sh[23573]:     return _end_unary_response_blocking(state, call, False, None)
Jul 12 07:35:04 sau-cca68-or sh[23573]:   File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
Jul 12 07:35:04 sau-cca68-or sh[23573]:     raise _InactiveRpcError(state)
Jul 12 07:35:04 sau-cca68-or sh[23573]: grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
Jul 12 07:35:04 sau-cca68-or sh[23573]:         status = StatusCode.OUT_OF_RANGE
Jul 12 07:35:04 sau-cca68-or sh[23573]:         details = "etcdserver: mvcc: required revision has been compacted"
Jul 12 07:35:04 sau-cca68-or sh[23573]:         debug_error_string = "{"created":"@1594539304.818078365","description":"Error received from peer ipv4:127.0.0.1:2379","fi
Jul 12 07:35:04 sau-cca68-or sh[23573]: >
Jul 12 07:35:08 sau-cca68-or sf main[23575]: Subprocess 23617 (cleaner) died
```

**Comment by mikalstill** [comment]
Sigh. This bug is causing the power state thing to not work because it crashes that daemon. I'm going to self merge a quick fix to unblock our victims.
