### ISSUE TITLE
Failed HTTP fetch of image leaves instance in initial state, not error state

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#155]
From syslog:

```
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='XXX.XXX.XXX.XXX', port=80): Max retries exceeded with url: /632684ed-69ab-4ea9-a51b-
8acdb947da57/csiro/cybertaipan_2020/01_indicative_ubuntu_14/001_disk_0.qcow2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection ob
ject at 0x7fd4205b6518>: Failed to establish a new connection: [Errno 110] Connection timed out',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 104, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 733, in post
        instance.create(lock=lock)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 155, in create
        images.requires_fetch(image_url)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 82, in requires_fetch
        headers={'User-Agent': util.get_user_agent()})
      File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='XXX.XXX.XXX.XXX', port=80): Max retries exceeded with url: /632684ed-69ab-4ea9-a51b-8acdb947da57/csiro/cybertaipan_2020/01_indicative_ubuntu_14/001_disk_0.qcow2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4205b6518>: Failed to establish a new connection: [Errno 110] Connection timed out',))
Jul 15 09:08:22 localhost gunicorn.sf.access: [25541] 127.0.0.1 - - [15/Jul/2020:09:08:22 +0000] "POST /instances HTTP/1.1" 500 4660 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.2.0"
```

The instance is left in the "initial" state, it should be in "error" state:

```
$ sf-client instance show 258660da-a283-40ce-85ee-617ae2a2257a
uuid        : 258660da-a283-40ce-85ee-617ae2a2257a
name        : indicative_ubuntu_14
namespace   : system
cpus        : 1
memory      : 1024
disk spec   : [{'base': 'http://10.152.15.214/632684ed-69ab-4ea9-a51b-8acdb947da57/csiro/cybertaipan_2020/01_indicative_ubuntu_14/001_disk_0.qcow2', 'bus': 'scsi', 'size': '20', 'type': 'disk'}]
node        : sf-1
state       : initial
console port: 47543
vdi port    : 43108

ssh key     : None
user data   : None

Metadata:

Interfaces:

    uuid    : 6276f0c8-6a86-4134-8767-4eac1f34328f
    network : 0b01d364-f448-41d5-a20b-673e54f2de17
    macaddr : 00:0c:29:41:b0:31
    order   : 0
    ipv4    : 192.168.0.207
    floating: None
```

And state should be shown in the instance listing:

```
$ sf-client instance list
+--------------------------------------+----------------------+-----------+------+--------+------------+
|                 uuid                 |         name         | namespace | cpus | memory | hypervisor |
+--------------------------------------+----------------------+-----------+------+--------+------------+
| 258660da-a283-40ce-85ee-617ae2a2257a | indicative_ubuntu_14 |   system  |  1   |  1024  |    sf-1    |
+--------------------------------------+----------------------+-----------+------+--------+------------+
```

**Comment by mikalstill** [comment]
I increasingly think this is something that is wrapped up in doing the instance start rewrite that we really need to do in v0.3. For now I want to focus on making v0.2 stable so that we can then move on to those features we can't do in v0.2. I am therefore bumping this to v0.3.

**Comment by mikalstill** [comment]
This should now be fixed by the queue rewrite.
