### ISSUE TITLE
Should lookup by name prefer the local namespace?

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1634]
```
INFO gunicorn: worker [sf-api][1547716] API request parsed; args=(); headers=Bearer *****; identity=None; kwargs={'configdrive': 'openstack-disk', 'cpus': 2, 'disk': [{'base': 'debian:11', 'bus': None, 'size': 5
0, 'type': 'disk'}], 'memory': 2048, 'metadata': {}, 'name': 'foo', 'namespace': None, 'network': [{'float': True, 'macaddress': None, 'model': 'virtio', 'network_uuid': 'foo'}], 'nvram_template': None, 'secure_boot': False, 'side_c
hannels': [], 'ssh_key': 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCm6MITeLtFxgXL9C/n9T52dibXBt+cX4P5yJxPSnLjNkkGrW7pB2ilMtb+fP/m+b98Dhh6LhMZ2SvN/AkxpLb6ZQFrPMEgP08kQGHKbGfk+juU0lt5aLIa7tiTi6dGHMNymxcWjDAEFVzS5rejUjIiR0TkjEXFSJpcBQoFq9
UrpS9oTqqYRrcs9LFmyRTXzmeqGWKlEqGMDTDhA0HbsxIKkbPPRlnF10YXIF2x8EtVBeAxLiVZ/XV5T36zOqSwdmcXXqK7wYtM66Ki3qNojg1xnllHQAWMQcgc8HcS2PR/k9yKZ7qmvGrBE6hiiNTMYWE//6dwLUIn5RQADyYvsAX/ mikal@sf-primary\n', 'uefi': False, 'user_data': None, 'v
ideo': {'memory': 16384, 'model': 'cirrus'}}; method=POST; path=/instances; request-id=a6f27c9a-7bb1-4706-9212-f8ed68c32875; url=http://192.168.1.53:13000/instances
INFO gunicorn: worker [sf-api][1547716] Added event; duration=None; fqdn=sf-3; keyname=deploy; message=Token used to authenticate request; method=POST; namespace=system; path=/instances; remote-address=192.168.1
.50; request-id=a6f27c9a-7bb1-4706-9212-f8ed68c32875; token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY3MTU3NDU0NywianRpIjoiMWFmYjc0ZjgtMjY4YS00NmU5LThmMTUtMTc4NDc0ZTUwMzczIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6WyJ
zeXN0ZW0iLCJkZXBsb3kiXSwibmJmIjoxNjcxNTc0NTQ3LCJleHAiOjE2NzE1NzU0NDcsImlzcyI6InNoYWtlbmZpc3QiLCJub25jZSI6ImFlbmROcWl1TWtMREFWbFQifQ.AxM43S0mf5Usz58-ZZk32RKRoVygATV3Q_x7_EqIkaw
ERROR gunicorn: worker [sf-api][1547716] Server error
Traceback (most recent call last):
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist_utilities/api.py", line 130, in wrapper
return func(*args, **kwargs)
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 139, in wrapper
return func(*args, **kwargs)
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 350, in wrapper
return func(*args, **kwargs)
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 162, in wrapper
return func(*args, **kwargs)
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/instance.py", line 242, in post
Artifact.from_url(Artifact.TYPE_IMAGE, disk_base,
File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/artifact.py", line 154, in from_url
raise exceptions.TooManyMatches()
shakenfist.exceptions.TooManyMatches
```

Or is this the correct behaviour?

**Comment by mikalstill** [comment]
Fixed. `Artifact.from_url` now prefers a single local-namespace match before raising `TooManyMatches` (`shakenfist/artifact.py:274-304`).

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
