### ISSUE TITLE
Undeletable instance on the CI cluster

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1653]
I get this traceback when I attempt to delete the instance:

```
sf-3 ERROR sf-queues-1671925876.4299061-YKh7T3rpbe2zj0lK[2619036] [Exception] Ignored error in instance instance(09b6844e-f970-43eb-866f-f79954ee74e0) delete task: No such network: 5a8bfd37-f6e5-491f-b3ab-b7b6f6450948
Traceback (most recent call last):
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 105, in handle
sf-3     instance_delete(inst)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 364, in instance_delete
sf-3     ni.delete()
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/networkinterface.py", line 175, in delete
sf-3     raise exceptions.NetworkMissing(
sf-3 shakenfist.exceptions.NetworkMissing: No such network: 5a8bfd37-f6e5-491f-b3ab-b7b6f6450948
```

**Comment by mikalstill** [comment]
Addressed by https://github.com/shakenfist/shakenfist/pull/1654 but I forgot to link it.
