### ISSUE TITLE
In place upgrades fight with etcd caching

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1667]
I know this one is about artifacts and node metrics, but I think this is probably more general than that:

```
Traceback (most recent call last):
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist_utilities/api.py", line 130, in wrapper
sf-3     return func(*args, **kwargs)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/flasgger/utils.py", line 273, in wrapper
sf-3     return function(*args, **kwargs)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 139, in wrapper
sf-3     return func(*args, **kwargs)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/base.py", line 162, in wrapper
sf-3     return func(*args, **kwargs)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/artifact.py", line 241, in get
sf-3     for a in Artifacts(filters=[
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/artifact.py", line 369, in __iter__
sf-3     a = Artifact.from_db(a['uuid'])
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/baseobject.py", line 91, in from_db
sf-3     return cls(static_values)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/artifact.py", line 58, in __init__
sf-3     if upgraded and gmov('artifact') == self.current_version:
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/metrics.py", line 56, in get_minimum_object_version
sf-3     metrics = get_node_metrics([])
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/metrics.py", line 19, in get_node_metrics
sf-3     new_metrics = etcd.get('metrics', n.uuid, None)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/etcd.py", line 168, in wrapper
sf-3     return func(*args, **kwargs)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/etcd.py", line 379, in get
sf-3     return cache.get(path)
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/etcd.py", line 142, in get
sf-3     self._cache_prefix(self._find_prefix(key))
sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/etcd.py", line 127, in _find_prefix
sf-3     raise ValueError('Attempt to cache etcd key without a UUID: %s' % key)
sf-3 ValueError: Attempt to cache etcd key without a UUID: /sf/metrics/sf-1/
```

**Comment by mikalstill** [comment]
This of course only happens just after an upgrade. If you wait a moment and try again your request will likely work. I need to ponder this some more.

**Comment by mikalstill** [comment]
Superseded. The etcd caching layer this describes no longer exists; object reads go through MariaDB, so in-place upgrades no longer fight etcd caching.

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
