### ISSUE TITLE
pycdlib has stopped making config drives

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1682]
I see this on the CI cluster:

```
Jan  1 10:25:46 Traceback (most recent call last):
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 101, in handle
Jan  1 10:25:46 sf-1     instance_start(inst, task.network())
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 323, in instance_start
Jan  1 10:25:46 sf-1     inst.create(iface_uuids, lock=lock)
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 611, in create
Jan  1 10:25:46 sf-1     self._configure_block_devices(lock)
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 735, in _configure_block_devices
Jan  1 10:25:46 sf-1     self._make_config_drive_openstack_disk(
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 869, in _make_config_drive_openstack_disk
Jan  1 10:25:46 sf-1     iso.new(interchange_level=4,
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/pycdlib.py", line 3895, in new
Jan  1 10:25:46 sf-1     self.pvd = headervd.pvd_factory(sys_ident_bytes, vol_ident_bytes,
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/headervd.py", line 809, in pvd_factory
Jan  1 10:25:46 sf-1     pvd.new(0, sys_ident, vol_ident, set_size, seqnum, log_block_size,
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/headervd.py", line 318, in new
Jan  1 10:25:46 sf-1     self.volume_creation_date.new(now)
Jan  1 10:25:46 sf-1   File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/dates.py", line 256, in new
Jan  1 10:25:46 sf-1     self.date_str = time.strftime(self.TIME_FMT, local).encode('utf-8') + '{:0<2}'.format(self.hundredthsofsecond).encode('utf-8') + struct.pack('=b', self.gmtoffset)
Jan  1 10:25:46 sf-1 struct.error: byte format requires -128 <= number <= 127
```

Which can be isolated as:

```
$ /srv/shakenfist/venv/bin/python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycdlib
>>> iso = pycdlib.PyCdlib()
>>> iso.new(interchange_level=4,
...                 joliet=True,
...                 rock_ridge='1.09',
...                 vol_ident='config-2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/pycdlib.py", line 3895, in new
    self.pvd = headervd.pvd_factory(sys_ident_bytes, vol_ident_bytes,
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/headervd.py", line 809, in pvd_factory
    pvd.new(0, sys_ident, vol_ident, set_size, seqnum, log_block_size,
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/headervd.py", line 318, in new
    self.volume_creation_date.new(now)
  File "/srv/shakenfist/venv/lib/python3.9/site-packages/pycdlib/dates.py", line 256, in new
    self.date_str = time.strftime(self.TIME_FMT, local).encode('utf-8') + '{:0<2}'.format(self.hundredthsofsecond).encode('utf-8') + struct.pack('=b', self.gmtoffset)
struct.error: byte format requires -128 <= number <= 127
```

**Comment by mikalstill** [comment]
In fact, even just calling `iso.new()` causes that stack trace.

**Comment by mikalstill** [comment]
Oh god. And now it's working again. Because the time changed.

**Comment by mikalstill** [comment]
Filed a bug upstream: [#107](https://github.com/clalancette/pycdlib/issues/107)

**Comment by mikalstill** [comment]
Upstream has fixed the bug, but not released the fixed quite yet.
