### ISSUE TITLE
Traceback should not be logged for MultipleObjects errors in the API

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1684]
```
Jan  5 11:38:54 sf-1 INFO gunicorn: worker [sf-api][2674485] Returning API error: 400, multiple networks have the name "external" in namespace "None"
Jan  5 11:38:54 sf-1     Traceback (most recent call last):
Jan  5 11:38:54 sf-1       File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/external_api/instance.py", line 303, in post
Jan  5 11:38:54 sf-1         n = sfnet.Network.from_db_by_ref(netdesc['network_uuid'])
Jan  5 11:38:54 sf-1       File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/baseobject.py", line 108, in from_db_by_ref
Jan  5 11:38:54 sf-1         raise exceptions.MultipleObjects(
Jan  5 11:38:54 sf-1     shakenfist.exceptions.MultipleObjects: multiple networks have the name "external" in namespace "None"
Jan  5 11:38:54 sf-1     
```

**Comment by mikalstill** [comment]
Additionally, these requests were for a key in a namespace, and that namespace should have been used to make these object references unique.
