### ISSUE TITLE
Supporting Ubuntu 22:04 requires being stricter about the format of backing images

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1701]
```
Jan 10 08:36:02 sf-5 ERROR sf-queues-1673339750.0848868-00AjkUNaY8nF8x8d[5737] [Exception] Ignored error in queue worker: Unexpected error while running command.
Jan 10 08:36:02 sf-5 Command: ionice -c 2 -n 7 qemu-img create -b /srv/shakenfist/image_cache/b18e598e-65b7-4550-8085-727e477d10bd.qcow2 -o cluster_size=2048K -f qcow2 /srv/shakenfist/instances/c33d14da-9398-4a52-9084-f42a1ef304f7/vda 8G
Jan 10 08:36:02 Exit code: 1
Jan 10 08:36:02 sf-5 Stdout: ''
Jan 10 08:36:02 sf-5 Stderr: 'qemu-img: /srv/shakenfist/instances/c33d14da-9398-4a52-9084-f42a1ef304f7/vda: Backing file specified without backing format\nDetected format of qcow2.'
Jan 10 08:36:02 Traceback (most recent call last):
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/daemons/queues.py", line 101, in handle
Jan 10 08:36:02 sf-5     instance_start(inst, task.network())
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/daemons/queues.py", line 323, in instance_start
Jan 10 08:36:02 sf-5     inst.create(iface_uuids, lock=lock)
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/instance.py", line 611, in create
Jan 10 08:36:02 sf-5     self._configure_block_devices(lock)
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/instance.py", line 815, in _configure_block_devices
Jan 10 08:36:02 sf-5     util_image.create_cow([lock], cached_image_path,
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/util/image.py", line 97, in create_cow
Jan 10 08:36:02 sf-5     util_process.execute(
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/shakenfist/util/process.py", line 54, in execute
Jan 10 08:36:02 sf-5     return processutils.execute(
Jan 10 08:36:02 sf-5   File "/srv/shakenfist/venv/lib/python3.10/site-packages/oslo_concurrency/processutils.py", line 438, in execute
Jan 10 08:36:02 sf-5     raise ProcessExecutionError(exit_code=_returncode,
Jan 10 08:36:02 sf-5 oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Jan 10 08:36:02 sf-5 Command: ionice -c 2 -n 7 qemu-img create -b /srv/shakenfist/image_cache/b18e598e-65b7-4550-8085-727e477d10bd.qcow2 -o cluster_size=2048K -f qcow2 /srv/shakenfist/instances/c33d14da-9398-4a52-9084-f42a1ef304f7/vda 8G
Jan 10 08:36:02 Exit code: 1
Jan 10 08:36:02 sf-5 Stdout: ''
Jan 10 08:36:02 sf-5 Stderr: 'qemu-img: /srv/shakenfist/instances/c33d14da-9398-4a52-9084-f42a1ef304f7/vda: Backing file specified without backing format\nDetected format of qcow2.'
```

**Comment by mikalstill** [comment]
The _hopefully_ relevant version changes between Debian 11 and Ubuntu 22.04:

```
$ diff -u /tmp/debian-11 /tmp/ubuntu-2204 | egrep "(qemu|libvirt)"
-    "gir1.2-libvirt-glib-1.0": "3.0.0-1",
-    "ipxe-qemu": "1.0.0+git-20190125.36a4c85-5.1",
+    "ipxe-qemu": "1.21.1+git-20220113.fbbdc3926-0ubuntu1",
+    "ipxe-qemu-256k-compat-efi-roms": "1.0.0+git-20150424.a25a16d-0ubuntu4",
-    "libvirt-clients": "7.0.0-3",
-    "libvirt-daemon": "7.0.0-3",
-    "libvirt-daemon-config-network": "7.0.0-3",
-    "libvirt-daemon-config-nwfilter": "7.0.0-3",
-    "libvirt-daemon-driver-lxc": "7.0.0-3",
-    "libvirt-daemon-driver-qemu": "7.0.0-3",
-    "libvirt-daemon-driver-vbox": "7.0.0-3",
-    "libvirt-daemon-driver-xen": "7.0.0-3",
-    "libvirt-daemon-system": "7.0.0-3",
-    "libvirt-daemon-system-systemd": "7.0.0-3",
-    "libvirt-dev": "7.0.0-3",
-    "libvirt-glib-1.0-0": "3.0.0-1",
-    "libvirt0": "7.0.0-3",
+    "libvirt-clients": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon-config-network": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon-config-nwfilter": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon-driver-qemu": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon-system": "8.0.0-1ubuntu7.4",
+    "libvirt-daemon-system-systemd": "8.0.0-1ubuntu7.4",
+    "libvirt-dev": "8.0.0-1ubuntu7.4",
+    "libvirt0": "8.0.0-1ubuntu7.4",
-    "python3-libvirt": "7.0.0-2",
+    "python3-libvirt": "8.0.0-1build1",
-    "qemu-system-common": "1:5.2+dfsg-11+deb11u2",
-    "qemu-system-data": "1:5.2+dfsg-11+deb11u2",
-    "qemu-system-gui": "1:5.2+dfsg-11+deb11u2",
-    "qemu-system-x86": "1:5.2+dfsg-11+deb11u2",
-    "qemu-utils": "1:5.2+dfsg-11+deb11u2",
+    "qemu-system-common": "1:6.2+dfsg-2ubuntu6.6",
+    "qemu-system-data": "1:6.2+dfsg-2ubuntu6.6",
+    "qemu-system-x86": "1:6.2+dfsg-2ubuntu6.6",
+    "qemu-utils": "1:6.2+dfsg-2ubuntu6.6",
```

**Comment by mikalstill** [comment]
So:

* libvirt goes from 7.0.0 to 8.0.0
* qemu goes from 1.5 to 1.6

**Comment by mikalstill** [comment]
I feel like this implies that I should also have some small amount of CI on Debian Testing (currently bookworm), which would help detect changes earlier.
