### ISSUE TITLE
Failure in CI: shakenfist_ci.tests.test_snapshots.TestSnapshots.test_multiple_disk_snapshots length mismatch

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1815]
```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/debian/shakenfist/deploy/shakenfist_ci/tests/test_snapshots.py", line 210, in test_multiple_disk_snapshots
    self.assertEqual(2, len(snapshots))

      File "/usr/lib/python3/dist-packages/testtools/testcase.py", line 415, in assertEqual
    self.assertThat(observed, matcher, message)

      File "/usr/lib/python3/dist-packages/testtools/testcase.py", line 502, in assertThat
    raise mismatch_error

    testtools.matchers._impl.MismatchError: 2 != 1
```

**Comment by mikalstill** [comment]
```
shakenfist_ci.tests.test_snapshots.TestSnapshots.test_multiple_disk_snapshots
-----------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/debian/shakenfist/deploy/shakenfist_ci/tests/test_snapshots.py", line 231, in test_multiple_disk_snapshots
    self.assertEqual(4, len(snapshots))

      File "/usr/lib/python3/dist-packages/testtools/testcase.py", line 415, in assertEqual
    self.assertThat(observed, matcher, message)

      File "/usr/lib/python3/dist-packages/testtools/testcase.py", line 502, in assertThat
    raise mismatch_error

    testtools.matchers._impl.MismatchError: 4 != 3
```
