### ISSUE TITLE
Traceback while creating instance

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1888]
```
Apr 18 14:51:34 sf-3 ERROR sf-queues-1681793491.8995912-26GkjfYIN7vlX698[904609] [Exception] Ignored error in queue worker: 'NoneType' object has no attribute 'modified'
Apr 18 14:51:34 Traceback (most recent call last):
Apr 18 14:51:34 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 83, in handle
Apr 18 14:51:34 sf-3     image_fetch(task.url(), n, inst)
Apr 18 14:51:34 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 243, in image_fetch
Apr 18 14:51:34 sf-3     images.ImageFetchHelper(inst, a).get_image()
Apr 18 14:51:34 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 118, in get_image
Apr 18 14:51:34 sf-3     fetched_blobs.append(self.transfer_image(lock))
Apr 18 14:51:34 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 162, in transfer_image
Apr 18 14:51:34 sf-3     if not most_recent_blob.modified:
Apr 18 14:51:34 sf-3 AttributeError: 'NoneType' object has no attribute 'modified'
```

**Comment by mikalstill** [comment]
The underlying blob was removed while the artifact still pointed at it:

```
sqlite> select * from events;
...
audit|1681249283.58656|sf-2||Overriding blob reference count with new value!|{"discovered_refs": ["artifact(1646bc22-674b-4a46-97e5-f767a6e82d1c)"], "new": 1, "old": 4}
mutate|1681249283.59574|sf-2||set reference count to 1|{}
mutate|1681284522.56606|sf-3||decremented reference count|{"instance": "f1f54814-7406-476b-bbe0-f974b6abc46d"}
mutate|1681284522.58176|sf-3||set attribute|{"attribute": "state", "update_time": 1681284522.5817556, "value": "deleted"}
audit|1681288127.68171|sf-1||hard deleted object|{}
```

Naughty reference count override.

**Comment by mikalstill** [comment]
The instance which was the other reference says this:

```
...
mutate|1681284521.49016|sf-3||set attribute|{"attribute": "state", "update_time": 1681284521.490147, "value": "delete-wait"}
mutate|1681284522.28006|sf-3||set attribute|{"attribute": "agent_state", "update_time": 1681284522.2800539, "value": "not ready (instance powered off)"}
audit|1681284522.28134|sf-3||sidechannel monitor finished|{}
mutate|1681284522.29906|sf-3||set attribute|{"attribute": "power_state", "power_state": "off", "power_state_previous": "on", "power_state_updated": 1681284522.2990487}
audit|1681284522.31317|sf-3||poweroff|{}
audit|1681284522.53571|sf-3||poweroff|{}
status|1681284522.54171|sf-3|0.00149631500244141|delete disks complete|{}
mutate|1681284522.67897|sf-3||set attribute|{"attribute": "state", "update_time": 1681284522.6789649, "value": "deleted"}
audit|1681288127.82535|sf-1||hard deleted object|{}

**Comment by mikalstill** [comment]
Merging those together:

```
1681249283.58656|sf-2||Overriding blob reference count with new value!|{"discovered_refs": ["artifact(1646bc22-674b-4a46-97e5-f767a6e82d1c)"], "new": 1, "old": 4}
1681249283.59574|sf-2||set reference count to 1|{}
1681284521.49016|sf-3||set attribute|{"attribute": "state", "update_time": 1681284521.490147, "value": "delete-wait"}
1681284522.28006|sf-3||set attribute|{"attribute": "agent_state", "update_time": 1681284522.2800539, "value": "not ready (instance powered off)"}
1681284522.28134|sf-3||sidechannel monitor finished|{}
1681284522.29906|sf-3||set attribute|{"attribute": "power_state", "power_state": "off", "power_state_previous": "on", "power_state_updated": 1681284522.2990487}
1681284522.31317|sf-3||poweroff|{}
1681284522.53571|sf-3||poweroff|{}
1681284522.54171|sf-3|0.00149631500244141|delete disks complete|{}
1681284522.56606|sf-3||decremented reference count|{"instance": "f1f54814-7406-476b-bbe0-f974b6abc46d"}
1681284522.58176|sf-3||set attribute|{"attribute": "state", "update_time": 1681284522.5817556, "value": "deleted"}
1681284522.67897|sf-3||set attribute|{"attribute": "state", "update_time": 1681284522.6789649, "value": "deleted"}
```

**Comment by mikalstill** [comment]
So why didn't the instance appear in the reference count before it entered delete-wait?

**Comment by mikalstill** [comment]
Oh, we're looking at the disk_spec not the block_devices in the cluster daemon.
