### ISSUE TITLE
Cleanup cluster lock on exit

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#1985]
After upgrading the CI cluster, I am getting heaps of:

```
Jun 17 20:10:30 sf-1 ERROR sf-main-v0.7.0[351215] Lock held by missing process on this node; node=sf-1; operation=Cluster maintenance; pid=351238
```

**Comment by mikalstill** [comment]
Seems to be this crash:

```
Jun 17 20:11:54 sf-3 sh[1031180]: Traceback (most recent call last):
Jun 17 20:11:54 sf-3 sh[1031180]:   File "/srv/shakenfist/venv/bin/sf-daemon-shim", line 8, in <module>
Jun 17 20:11:54 sf-3 sh[1031180]:     sys.exit(main())
Jun 17 20:11:54 sf-3 sh[1031180]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/shim.py", line 34, in main
Jun 17 20:11:54 sf-3 sh[1031180]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Jun 17 20:11:54 sf-3 sh[1031180]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cluster.py", line 408, in run
Jun 17 20:11:54 sf-3 sh[1031180]:     self._cluster_wide_cleanup(last_loop_run)
Jun 17 20:11:54 sf-3 sh[1031180]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cluster.py", line 351, in _cluster_wide_cleanup
Jun 17 20:11:54 sf-3 sh[1031180]:     for obj in hd.keys():
Jun 17 20:11:54 sf-3 sh[1031180]: RuntimeError: dictionary changed size during iteration
```

**Comment by mikalstill** [comment]
Sigh.

```
Jun 17 20:21:10 sf-2 sh[1209488]: Traceback (most recent call last):
Jun 17 20:21:10 sf-2 sh[1209488]:   File "/srv/shakenfist/venv/bin/sf-daemon-shim", line 8, in <module>
Jun 17 20:21:10 sf-2 sh[1209488]:     sys.exit(main())
Jun 17 20:21:10 sf-2 sh[1209488]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/shim.py", line 34, in main
Jun 17 20:21:10 sf-2 sh[1209488]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Jun 17 20:21:10 sf-2 sh[1209488]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cluster.py", line 409, in run
Jun 17 20:21:10 sf-2 sh[1209488]:     self._cluster_wide_cleanup(last_loop_run)
Jun 17 20:21:10 sf-2 sh[1209488]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cluster.py", line 352, in _cluster_wide_cleanup
Jun 17 20:21:10 sf-2 sh[1209488]:     for obj in copy.copy(hd.keys()):
Jun 17 20:21:10 sf-2 sh[1209488]:   File "/usr/lib/python3.9/copy.py", line 92, in copy
Jun 17 20:21:10 sf-2 sh[1209488]:     rv = reductor(4)
Jun 17 20:21:10 sf-2 sh[1209488]: TypeError: cannot pickle 'dict_keys' object
```
