### ISSUE TITLE
Chase down image fetch failures seen on the CI cluster

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#2021]
I'm not sure what's happening here:

```
Jul 30 02:13:02 sf-3 ERROR sf-queues-1690647181.299146-UORuA2k5PfcofNex[3109003] [Exception] Ignored error in queue worker: Failed to parse: //ubuntu:22.04/latest.qcow2
Jul 30 02:13:02 Traceback (most recent call last):
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/urllib3/util/url.py", line 425, in parse_url
Jul 30 02:13:02 sf-3     host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
Jul 30 02:13:02 sf-3 AttributeError: 'NoneType' object has no attribute 'groups'
Jul 30 02:13:02 The above exception was the direct cause of the following exception:
Jul 30 02:13:02 Traceback (most recent call last):
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 84, in handle
Jul 30 02:13:02 sf-3     image_fetch(task.url(), n, inst)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/queues.py", line 244, in image_fetch
Jul 30 02:13:02 sf-3     images.ImageFetchHelper(inst, a).get_image()
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 118, in get_image
Jul 30 02:13:02 sf-3     fetched_blobs.append(self.transfer_image(lock))
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 210, in transfer_image
Jul 30 02:13:02 sf-3     b = self._http_get_inner(lock, url, checksum, checksum_type,
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 328, in _http_get_inner
Jul 30 02:13:02 sf-3     resp = self._open_connection(url)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/images.py", line 353, in _open_connection
Jul 30 02:13:02 sf-3     resp = requests.get(url, allow_redirects=True, stream=True,
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
Jul 30 02:13:02 sf-3     return request("get", url, params=params, **kwargs)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
Jul 30 02:13:02 sf-3     return session.request(method=method, url=url, **kwargs)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
Jul 30 02:13:02 sf-3     resp = self.send(prep, **send_kwargs)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
Jul 30 02:13:02 sf-3     r = adapter.send(request, **kwargs)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
Jul 30 02:13:02 sf-3     resp = conn.urlopen(
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 708, in urlopen
Jul 30 02:13:02 sf-3     parsed_url = parse_url(url)
Jul 30 02:13:02 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/urllib3/util/url.py", line 451, in parse_url
Jul 30 02:13:02 sf-3     raise LocationParseError(source_url) from e
Jul 30 02:13:02 sf-3 urllib3.exceptions.LocationParseError: Failed to parse: //ubuntu:22.04/latest.qcow2
```

**Comment by mikalstill** [comment]
Its confusing. Here's what happens when I do a `sf-client artifact cache ubuntu:20.04`:

```
Jul 31 20:15:54 sf-3 INFO gunicorn: worker [sf-api][3312234] Enqueued workitem; jobname=1690798554.6187272-OXMWzYi6k19xmF0a; queuename=sf-3; request-id=287ca828-2d39-4cca-bde1-d37983b901f2; workitem={'tasks': [QueueTask:Fet
chImageTask: {'task': 'image_fetch', 'version': 1, 'url': 'ubuntu:20.04', 'namespace': 'system', 'instance_uuid': None}]}
Jul 31 20:15:54 sf-3 INFO sf-queues[3312138] Moved workitem from queue to processing; jobname=1690798554.6187272-OXMWzYi6k19xmF0a; queuename=sf-3; workitem={'tasks': [QueueTask:FetchImageTask: {'task': 'image_fetch', 'versi
on': 1, 'url': 'ubuntu:20.04', 'namespace': 'system', 'instance_uuid': None}]}
Jul 31 20:15:54 sf-3 INFO sf-queues[3379363] Starting <function handle at 0x7f3725f5e0d0> with args ('1690798554.6187272-OXMWzYi6k19xmF0a', {'tasks': [QueueTask:FetchImageTask: {'task': 'image_fetch', 'version': 1, 'url': '
ubuntu:20.04', 'namespace': 'system', 'instance_uuid': None}]})
Jul 31 20:15:54 sf-3 INFO sf-queues[3379363] Processing workitem; workitem=1690798554.6187272-OXMWzYi6k19xmF0a
Jul 31 20:15:54 sf-3 INFO sf-queues-1690798554.6187272-OXMWzYi6k19xmF0a[3379363] Starting task; task_name=image_fetch; workitem=1690798554.6187272-OXMWzYi6k19xmF0a
Jul 31 20:15:54 sf-3 INFO sf-queues-1690798554.6187272-OXMWzYi6k19xmF0a[3379363] Cluster does not have a copy of image; artifact=1516f74b-a229-4c70-b988-217956ff6291
Jul 31 20:15:54 sf-3 INFO sf-queues-1690798554.6187272-OXMWzYi6k19xmF0a[3379363] Fetching image from the internet; artifact=1516f74b-a229-4c70-b988-217956ff6291
Jul 31 20:15:55 sf-3 ERROR sf-queues-1690798554.6187272-OXMWzYi6k19xmF0a[3379363] [Exception] Ignored error in queue worker: Failed to parse: //ubuntu:20.04/latest.qcow2
```

**Comment by mikalstill** [comment]
This seems to now be fixed, so I guess we chalk it up to yet another piece of pydantic 2.0 fallout.
