### ISSUE TITLE
Debian 11 permissions problem with removing instances

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#2150]
I am unsure why I don't see this in CI. We try to delete an instance:

```
Dec  8 01:26:46 ci-5 INFO sf-queues[213225] Moved workitem from queue to processing; jobname=1701998354.8749263-5EMiEMhKHKIy8oD9; queuename=sf-5; workitem={'tasks': [QueueTask:DeleteInstanceTask: {'task': 'instance_delete', 'version': 1, 'instance_uuid': 'fb47bd9d-be4c-4b00-9e0a-d2a4165cc717', 'network': []}]}
Dec  8 01:26:46 ci-5 INFO sf-queues-1701998354.8749263-5EMiEMhKHKIy8oD9[213278] Starting task; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; task_name=instance_delete; workitem=1701998354.8749263-5EMiEMhKHKIy8oD9
Dec  8 01:26:46 ci-5 kernel: [178909.591835] audit: type=1400 audit(1701998806.827:614): apparmor="DENIED" operation="signal" profile="libvirt-fb47bd9d-be4c-4b00-9e0a-d2a4165cc717" pid=42829 comm="rpc-worker" requested_mask="receive" denied_mask="receive" signal=term peer="libvirtd"
Dec  8 01:26:46 ci-5 ERROR sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Failed to delete domain: Failed to terminate process 153482 with SIGTERM: Permission denied; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717
Dec  8 01:26:46 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; attribute=agent_state; duration=None; event_type=mutate; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=set attribute; update_time=1701998806.833424; value=not ready (instance powered off)
Dec  8 01:26:46 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; attribute=power_state; duration=None; event_type=mutate; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=set attribute; power_state=off; power_state_previous=on; power_state_updated=1701998806.8500628
Dec  8 01:26:46 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; duration=None; event_type=audit; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=poweroff
Dec  8 01:26:49 ci-5 ERROR sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Failed to delete domain: Failed to terminate process 153482 with SIGTERM: Permission denied; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717
Dec  8 01:26:49 ci-5 kernel: [178912.745007] audit: type=1400 audit(1701998809.979:615): apparmor="DENIED" operation="signal" profile="libvirt-fb47bd9d-be4c-4b00-9e0a-d2a4165cc717" pid=42829 comm="prio-rpc-worker" requested_mask="receive" denied_mask="receive" signal=term peer="libvirtd"
Dec  8 01:26:50 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; duration=None; event_type=audit; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=poweroff
Dec  8 01:26:50 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; duration=0.00035643577575683594; event_type=status; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=delete disks complete
Dec  8 01:26:50 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; attribute=blob_references; duration=None; event_type=mutate; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=set attribute
Dec  8 01:26:50 ci-5 INFO sf-queues-1701998153.3479216-ciSrmy8dg5jpEEom[213271] Added event; attribute=state; duration=None; event_type=mutate; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717; message=set attribute; update_time=1701998810.2208235; value=deleted
```

The cleaner dutifully tries to cleanup the mess:

```
Dec  8 01:35:36 ci-5 WARNING sf-cleaner[214724] Deleting stray instance; attempt=4; instance=fb47bd9d-be4c-4b00-9e0a-d2a4165cc717
Dec  8 01:36:43 ci-5 INFO sf-cleaner[214724] Added event; attribute=enforced_deletes; count=5; duration=None; event_type=mutate; fqdn=sf-5; instance=fb47bd9d-be4c-4b00-9e0a-d2a
4165cc717; message=set attribute
Dec  8 01:36:43 ci-5 kernel: [179506.625433] audit: type=1400 audit(1701999403.864:693): apparmor="DENIED" operation="signal" profile="libvirt-fb47bd9d-be4c-4b00-9e0a-d2a4165cc
717" pid=42829 comm="rpc-worker" requested_mask="receive" denied_mask="receive" signal=term peer="libvirtd"
Dec  8 01:36:43 ci-5 ERROR sf-cleaner[214724] Failed to delete domain: Failed to terminate process 153482 with SIGTERM: Permission denied; instance=fb47bd9d-be4c-4b00-9e0a-d2a4
165cc717
```

Note the apparmor log line above. This is happening because the apparmor profile for the instance has been removed by this point. Eventually SF tries to use the command line to delete the instance instead, which also fails:

```
Dec  8 02:06:07 ci-5 INFO sf-cleaner[225910] Executing virsh undefine --nvram "sf:fb47bd9d-be4c-4b00-9e0a-d2a4165cc717" with locks None
Dec  8 02:06:07 ci-5 sh[225910]: Traceback (most recent call last):
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/bin/sf-daemon-shim", line 8, in <module>
Dec  8 02:06:07 ci-5 sh[225910]:     sys.exit(main())
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/shim.py", line 34, in main
Dec  8 02:06:07 ci-5 sh[225910]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cleaner.py", line 385, in run
Dec  8 02:06:07 ci-5 sh[225910]:     self._update_power_states()
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/cleaner.py", line 81, in _update_power_states
Dec  8 02:06:07 ci-5 sh[225910]:     util_process.execute(
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/util/process.py", line 45, in execute
Dec  8 02:06:07 ci-5 sh[225910]:     return processutils.execute(
Dec  8 02:06:07 ci-5 sh[225910]:   File "/srv/shakenfist/venv/lib/python3.9/site-packages/oslo_concurrency/processutils.py", line 438, in execute
Dec  8 02:06:07 ci-5 sh[225910]:     raise ProcessExecutionError(exit_code=_returncode,
Dec  8 02:06:07 ci-5 sh[225910]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Dec  8 02:06:07 ci-5 sh[225910]: Command: virsh undefine --nvram "sf:fb47bd9d-be4c-4b00-9e0a-d2a4165cc717"
Dec  8 02:06:07 ci-5 sh[225910]: Exit code: 1
Dec  8 02:06:07 ci-5 sh[225910]: Stdout: '\n'
Dec  8 02:06:07 ci-5 sh[225910]: Stderr: "error: Failed to undefine domain 'sf:fb47bd9d-be4c-4b00-9e0a-d2a4165cc717'\nerror: Requested operation is not valid: cannot undefine transient domain\n"
```

We should also add `apparmor="DENIED"` as a banned phrase in CI logs for sure, but there is more to do here.

**Comment by mikalstill** [comment]
Fix by https://github.com/shakenfist/shakenfist/pull/2151, but I am bad at commit message comments.
