### ISSUE TITLE
Issue in CI cluster, kvm_pid lookup fails

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#2324]
Lots and lots of these:

```
Mar 14 19:54:41 Traceback (most recent call last):
Mar 14 19:54:41 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/resources.py", line 428, in run
Mar 14 19:54:41 sf-3     emit_billing_statistics()
Mar 14 19:54:41 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/daemons/resources.py", line 354, in emit_billing_statistics
Mar 14 19:54:41 sf-3     pid = inst.kvm_pid
Mar 14 19:54:41 sf-3   File "/srv/shakenfist/venv/lib/python3.9/site-packages/shakenfist/instance.py", line 512, in kvm_pid
Mar 14 19:54:41 sf-3     return self._db_get_attribute('kvm_pid').get('pid')
Mar 14 19:54:41 sf-3 AttributeError: 'int' object has no attribute 'get'
```

**Comment by mikalstill** [comment]
I think this is because I changed the format of that attribute and messed up the upgrade...
