### ISSUE TITLE
Triggers has started logging an exception

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#243]
Just dropping this here so that we remember.

```
Jul 31 17:55:27 sf-3 sh[12531]: Process sf trigger 96053817-1ac3-4a33-a595-bfb6478a5218:
Jul 31 17:55:27 sf-3 sh[12531]: Traceback (most recent call last):
Jul 31 17:55:27 sf-3 sh[12531]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Jul 31 17:55:27 sf-3 sh[12531]:     self.run()
Jul 31 17:55:27 sf-3 sh[12531]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
Jul 31 17:55:27 sf-3 sh[12531]:     self._target(*self._args, **self._kwargs)
Jul 31 17:55:27 sf-3 sh[12531]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/triggers.py", line 35, in observe
Jul 31 17:55:27 sf-3 sh[12531]:     d = os.read(fd, 1024).decode('utf-8')
Jul 31 17:55:27 sf-3 sh[12531]: UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data
Jul 31 17:55:27 sf-3 Trigger observer for instance 96053817-1ac3-4a33-a595-bfb6478a5218 has terminated
Jul 31 17:55:27 sf-3 Started trigger observer for instance 96053817-1ac3-4a33-a595-bfb6478a5218
Jul 31 17:55:27 sf-3 Monitoring /srv/shakenfist/instances/96053817-1ac3-4a33-a595-bfb6478a5218/console.log for triggers
Jul 31 17:55:34 sf-3 Trigger login prompt matched for instance 96053817-1ac3-4a33-a595-bfb6478a5218

```

**Comment by mikalstill** [comment]
What distro type was this instance?

**Comment by mikalstill** [comment]
I haven't been able to re-create this.
