### ISSUE TITLE
Catch error in API from caused by bad user data

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#244]
Catch this exception.  Caused by typo supplying userdata.

```
Jul 31 20:16:57 sf-3 API request: POST http://sf-3:13000/instances
    Headers:
        ('Host', 'sf-3:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTYxOTA2MTYsIm5iZiI6MTU5NjE5MDYxNiwianRpIjoiNzY1ZGEyOTktYWQ3ZS00ODlkLTk1NTgtNDI1NmRhZWNiMzAzIiwiZXhwIjoxNTk2MTkxNTE2LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.F6CCoS8cNQTY5eYx9w7X6If9AU62IF1fYaeZvhmUd34')
        ('Content-Length', '428')
    Args: ()
    KWargs: {'name': 'callhome0', 'cpus': 2, 'memory': 1024, 'network': [{'network_uuid': '0e766fda-b5fc-40b1-9f96-e69bbb5cf590', 'address': '', 'macaddress': '', 'model': ''}], 'disk': [{'base': 'ubuntu', 'size': 8, 'bus': '', 'type': 'disk'}], 'video': {'model': 'cirrus', 'memory': 16384}, 'ssh_key': '', 'user_data': 'phone-home.yaml', 'placed_on': 'sf-3', 'instance_uuid': '151573ce-0d55-44c8-92e8-05d994df2b82', 'namespace': 'system'}
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] forced as candidates
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] start as candidates
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have enough actual CPU
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have enough idle CPU
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have enough idle RAM
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have enough idle disk
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have most matching networks
Jul 31 20:16:57 sf-3 Scheduling instance(151573ce-0d55-44c8-92e8-05d994df2b82), ['sf-3'] have most matching images
Jul 31 20:16:57 sf-3 instance(151573ce-0d55-44c8-92e8 Finish schedule, duration 0.15 seconds
Jul 31 20:16:57 sf-3 Fetching system auth token from http://192.168.72.201:13000/auth
Jul 31 20:16:57 sf-1 API request: POST http://192.168.72.201:13000/auth
    Headers:
        ('Host', '192.168.72.201:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'qwsebytfefmkdtnfveaqsomxohmlnremmwkialhucrasbvbxpq'}
Jul 31 20:16:57 localhost gunicorn.sf.access: [14119] 192.168.72.203 - - [31/Jul/2020:20:16:57 +1000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Jul 31 20:16:57 sf-1 API request: PUT http://192.168.72.201:13000/deploy_network_node
    Headers:
        ('Host', '192.168.72.201:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTYxOTA2MTcsIm5iZiI6MTU5NjE5MDYxNywianRpIjoiNWNmZWI0MTMtZDc0ZC00YjYyLWJhODctMDJjYjczMjY4N2YzIiwiZXhwIjoxNTk2MTkxNTE3LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.XMf1cdG5Jkd37LbHwOIzEIEGhEeWo38p-v3E-R0VtV0')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': '0e766fda-b5fc-40b1-9f96-e69bbb5cf590'}
Jul 31 20:16:57 sf-1 network(0e766fda-b5fc-40b1-9f96-e69bbb5cf590, vxid 1): Finish enable nat, duration 0.15 seconds
Jul 31 20:16:57 sf-1 dnsmasq-dhcp[14302]: read /srv/shakenfist/dhcp/0e766fda-b5fc-40b1-9f96-e69bbb5cf590/hosts
Jul 31 20:16:57 sf-1 network(0e766fda-b5fc-40b1-9f96-e69bbb5cf590, vxid 1): Finish update dhcp, duration 0.13 seconds
Jul 31 20:16:57 localhost gunicorn.sf.access: [14119] 192.168.72.203 - - [31/Jul/2020:20:16:57 +1000] "PUT /deploy_network_node HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Jul 31 20:16:58 sf-1 API request: POST http://192.168.72.201:13000/auth
    Headers:
        ('Host', '192.168.72.201:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Content-Type', 'application/json')
        ('Content-Length', '84')
    Args: ()
    KWargs: {'namespace': 'system', 'key': 'qwsebytfefmkdtnfveaqsomxohmlnremmwkialhucrasbvbxpq'}
Jul 31 20:16:58 localhost gunicorn.sf.access: [14119] 192.168.72.203 - - [31/Jul/2020:20:16:58 +1000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Jul 31 20:16:58 sf-1 API request: PUT http://192.168.72.201:13000/update_dhcp
    Headers:
        ('Host', '192.168.72.201:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTYxOTA2MTgsIm5iZiI6MTU5NjE5MDYxOCwianRpIjoiYmQ4NjZkNGQtODFjNi00OTJiLWEyZTctYTkzOWRjMDk5ZjA0IiwiZXhwIjoxNTk2MTkxNTE4LCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.QB-mQz8QUBPVMd4gwdcefL8yP3ZVmkgObDVK_7MzMns')
        ('Content-Length', '48')
    Args: ()
    KWargs: {'passed_uuid': '0e766fda-b5fc-40b1-9f96-e69bbb5cf590'}
Jul 31 20:16:58 sf-1 dnsmasq-dhcp[14302]: read /srv/shakenfist/dhcp/0e766fda-b5fc-40b1-9f96-e69bbb5cf590/hosts
Jul 31 20:16:58 sf-1 network(0e766fda-b5fc-40b1-9f96-e69bbb5cf590, vxid 1): Finish update dhcp, duration 0.14 seconds
Jul 31 20:16:58 localhost gunicorn.sf.access: [14116] 192.168.72.203 - - [31/Jul/2020:20:16:58 +1000] "PUT /update_dhcp HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Jul 31 20:16:58 sf-3 Fetching system auth token from http://192.168.72.201:13000/auth
Jul 31 20:16:58 sf-3 instance(151573ce-0d55-44c8-92e8 Finish ensure networks exist, duration 0.45 seconds
Jul 31 20:16:58 sf-3 instance(151573ce-0d55-44c8-92e8 Finish make config drive, duration 0.02 seconds
Jul 31 20:16:58 sf-3 instance(151573ce-0d55-44c8-92e8 Finish instance creation, duration 0.07 seconds
Jul 31 20:16:58 sf-3 Returning API error: 500, server error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 108, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 683, in post
        return self._instance_start(instance_uuid, instance, network, namespace, placed_on)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 728, in _instance_start
        return self._instance_start_local(instance_uuid, instance, network, namespace)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 831, in _instance_start_local
        instance.create(lock=lock)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 156, in create
        self.instance_path, self.db_entry['block_devices']['devices'][1]['path']))
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 320, in _make_config_drive
        user_data = base64.b64decode(self.db_entry['user_data'])
      File "/usr/lib/python3.6/base64.py", line 87, in b64decode
        return binascii.a2b_base64(s)
    binascii.Error: Incorrect padding
```

**Comment by mikalstill** [comment]
Closing during a triage sweep of old issues: superseded by #3269, which tracks the same problem (unfriendly API failure when user_data is not valid base64) against the current codebase with a clearer statement of the desired behaviour.

*(Triage assisted by Claude Code; closure approved by Michael Still.)*
