### ISSUE TITLE
Images lock problem

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#249]
*Possibly* related to PR #224 
```
Aug  1 04:51:20 sau-3f41e-or instance(54963a87-54e7-412c-b8cd Finish fetch image, duration 2.57 seconds
Aug  1 04:51:20 sau-3f41e-or instance(54963a87-54e7-412c-b8cd Finish instance creation, duration 12.66 seconds
Aug  1 04:51:20 sau-3f41e-or Returning API error: 500, server error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 108, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 683, in post
        return self._instance_start(instance_uuid, instance, network, namespace, placed_on)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 728, in _instance_start
        return self._instance_start_local(instance_uuid, instance, network, namespace)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 831, in _instance_start_local
        instance.create(lock=lock)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py", line 172, in create
        info, resp, locks=[lock, image_lock])
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 116, in fetch
        bump_locks(locks)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 102, in bump_locks
        lock.refresh()
      File "/usr/local/lib/python3.6/dist-packages/etcd3/locks.py", line 123, in refresh
        raise ValueError('No lease associated with this lock - have you '
    ValueError: No lease associated with this lock - have you acquired the lock yet?
Aug  1 04:51:20 sau-cca68-or Returning proxied request: 500, {"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):
\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 108, in wrapper\n    return func(*args, **kwargs)\n  File \"/
usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 108, in wrapper\n    return fn(*args, **kwargs)\n  File \"/usr/loc
al/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 683, in post\n    return self._instance_start(instance_uuid, instance, network, 
namespace, placed_on)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 728, in _instance_start\n    return self
._instance_start_local(instance_uuid, instance, network, namespace)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\",
 line 831, in _instance_start_local\n    instance.create(lock=lock)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/virt.py\", line 172, i
n create\n    info, resp, locks=[lock, image_lock])\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/images.py\", line 116, in fetch\n    b
ump_locks(locks)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/images.py\", line 102, in bump_locks\n    lock.refresh()\n  File \"/usr/l
ocal/lib/python3.6/dist-packages/etcd3/locks.py\", line 123, in refresh\n    raise ValueError('No lease associated with this lock - have you '\nValueE
rror: No lease associated with this lock - have you acquired the lock yet?\n"}
```

**Comment by mikalstill** [comment]
I think this is happening when an image fetch takes too long, and the gunicorn worker is killed mid fetch. The lock then hangs around until it times out two minutes later. It seems to be happening a lot for Ubuntu downloads today, their servers are slow for some reason.

**Comment by mikalstill** [comment]
Oh, I have a re-write in mind for this for v0.3, but am avoiding doing a disruptive thing right now.
