### ISSUE TITLE
Error during instance start

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#263]
```
Error: Unable to create instance: request error: httpRequest error: received non 200 status code: 500 - {"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 116, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 108, in wrapper\n    return fn(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 688, in post\n    return self._instance_start(instance_uuid, instance, network, namespace, placed_on)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 733, in _instance_start\n    return self._instance_start_local(instance_uuid, instance, network, namespace)\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 829, in _instance_start_local\n    n.ensure_mesh()\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/net.py\", line 366, in ensure_mesh\n    discovered = list(self.discover_mesh())\n  File \"/usr/local/lib/python3.6/dist-packages/shakenfist/net.py\", line 330, in discover_mesh\n    shell=True)\n  File \"/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py\", line 434, in execute\n    cmd=sanitized_cmd)\noslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.\nCommand: bridge fdb show brport vxlan-8\nExit code: 255\nStdout: ''\nStderr: 'Cannot find device \"vxlan-8\"\\n'\n"}
```

**Comment by mandoonandy** [comment]
```
Aug  3 04:48:23 sau-2d4a1-or API request: POST http://sf-2:13000/instances
    Headers:
        ('Host', 'sf-2:13000')
        ('User-Agent', 'Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.2.4')
        ('Accept-Encoding', 'gzip, deflate')
        ('Accept', '*/*')
        ('Connection', 'keep-alive')
        ('Authorization', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTY0MzAxMDMsIm5iZiI6MTU5NjQzMDEwMywianRpIjoiYzFlOWYzYTUtMTY1My00NWQ3LTg5NjItYTdkZGI4NGNiMzc1IiwiZXhwIjoxNTk2NDMxMDAzLCJpZGVudGl0eSI6InN5c3RlbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.B3A-OMWMKDJ-
1RcQmobIsAUFIyZmQNtSNRER4fX8leU')
        ('Content-Length', '593')
    Args: ()
    KWargs: {'name': 'labtalk-vm-41f339e5-2df6-47af-ba40-c5729eaf4d91', 'cpus': 2, 'memory': 8192, 'network': [{'network_uuid': '7f9cb23c-66cf-4264-821a-4be34ffa02a5', 'address
': '', 'macaddress': '00:0c:29:2e:ad:06', 'model': 'e1000'}], 'disk': [{'base': 'http://10.152.15.214/632684ed-69ab-4ea9-a51b-8acdb947da57/csiro/cybertaipan_2020/02_training_ubuntu_16/001_disk_0.qcow2', 'size': 20, 'bus': 'virtio', 'type': 'disk'}], 'video': {'model': 'cirrus', 'memory': 16384}, 'ssh_key': '', 'user_data': '', 'placed_on': 'sf-2', 'instance_uuid': 'd3b3fbe0-f850-4028-a2f3-8390348a6614', 'namespace': 'system'}
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] forced as candidates
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] start as candidates
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have enough actual CPU
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have enough idle CPU
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have enough idle RAM
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have enough idle disk
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe), ['sf-2'] have most matching networks
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe), ['sf-2'] have most matching images
Aug  3 04:48:23 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish schedule, duration 0.15 seconds
Aug  3 04:48:23 sau-2d4a1-or Fetching system auth token from http://10.2.1.11:13000/auth
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have most matching networks
Aug  3 04:48:23 sau-2d4a1-or Scheduling instance(d3b3fbe0-f850-4028-a2f3-8390348a6614), ['sf-2'] have most matching images
Aug  3 04:48:23 sau-2d4a1-or instance(d3b3fbe0-f850-4028-a2f3-8390348a6614): Finish schedule, duration 0.17 seconds
Aug  3 04:48:23 sau-2d4a1-or Fetching system auth token from http://10.2.1.11:13000/auth
Aug  3 04:48:24 sau-2d4a1-or Fetching system auth token from http://10.2.1.11:13000/auth
Aug  3 04:48:24 sau-2d4a1-or Fetching message repeated 2 times: [ system auth token from http://10.2.1.11:13000/auth]
Aug  3 04:48:24 sau-2d4a1-or Extra vxlans present! IDs are: [8]
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish ensure networks exist, duration 1.35 seconds
Aug  3 04:48:25 sau-2d4a1-or systemd-timesyncd[1245]: Network configuration changed, trying to establish connection.
Aug  3 04:48:25 sau-2d4a1-or kernel: [430065.181310] device vxlan-8 left promiscuous mode
Aug  3 04:48:25 sau-2d4a1-or kernel: [430065.181382] br-vxlan-8: port 1(vxlan-8) entered disabled state
Aug  3 04:48:25 sau-2d4a1-or networkd-dispatcher[1576]: WARNING:Unknown index 417 seen, reloading interface list
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish make config drive, duration 0.04 seconds
Aug  3 04:48:25 sau-2d4a1-or systemd-networkd[1433]: br-vxlan-8: Link DOWN
Aug  3 04:48:25 sau-2d4a1-or systemd-networkd[1433]: br-vxlan-8: Lost carrier
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish fetch image, duration 0.02 seconds
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish transcode image, duration 0.01 seconds
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish resize image, duration 0.01 seconds
Aug  3 04:48:25 sau-2d4a1-or network(7f9cb23c-66cf-4264-821a-4be34ffa02a5, vxid 8): Finish delete vxlan bridge, duration 0.11 seconds
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish create copy on write layer, duration 0.02 seconds
Aug  3 04:48:25 sau-2d4a1-or systemd-networkd[1433]: vxlan-8: Link DOWN
Aug  3 04:48:25 sau-2d4a1-or systemd-networkd[1433]: vxlan-8: Lost carrier
Aug  3 04:48:25 sau-2d4a1-or systemd-networkd[1433]: vxlan-8: Removing non-existent address: fe80::3898:77ff:fe5b:d959/64 (valid forever), ignoring
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Finish create domain XML, duration 0.04 seconds
Aug  3 04:48:25 sau-2d4a1-or instance(3d8bceb7-5bb5-49b2-97dc-778299e953fe): Failed to lookup domain
Aug  3 04:48:25 sau-2d4a1-or network(7f9cb23c-66cf-4264-821a-4be34ffa02a5, vxid 8): Finish delete vxlan interface, duration 0.26 seconds
Aug  3 04:48:25 sau-2d4a1-or Extra vxlan 8 (network 7f9cb23c-66cf-4264-821a-4be34ffa02a5) removed.
Aug  3 04:48:25 sau-2d4a1-or kernel: [430065.682854] audit: type=1400 audit(1596430105.991:2017): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirt-3d8bceb7-5bb5-49b2-97dc-778299e953fe" pid=12665 comm="apparmor_parser"
Aug  3 04:48:26 sau-2d4a1-or instance(d3b3fbe0-f850-4028-a2f3-8390348a6614): Finish ensure networks exist, duration 0.03 seconds
Aug  3 04:48:26 sau-2d4a1-or Returning API error: 500, server error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 116, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 688, in post
        return self._instance_start(instance_uuid, instance, network, namespace, placed_on)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 733, in _instance_start
        return self._instance_start_local(instance_uuid, instance, network, namespace)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 829, in _instance_start_local
        n.ensure_mesh()
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 366, in ensure_mesh
        discovered = list(self.discover_mesh())
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 330, in discover_mesh
        shell=True)
      File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 434, in execute
        cmd=sanitized_cmd)
    oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
    Command: bridge fdb show brport vxlan-8
    Exit code: 255
    Stdout: ''
    Stderr: 'Cannot find device "vxlan-8"\n'
Aug  3 04:48:26 sau-2d4a1-or kernel: [430065.884176] audit: type=1400 audit(1596430106.195:2018): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-3d8bceb7-5bb5-49b2-97dc-778299e953fe" pid=12681 comm="apparmor_parser"
Aug  3 04:48:26 sau-2d4a1-or kernel: [430066.087766] audit: type=1400 audit(1596430106.399:2019): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-3d8bceb7-5bb5-49b2-97dc-778299e953fe" pid=12684 comm="apparmor_parser"
Aug  3 04:48:26 sau-2d4a1-or instance(89c9c60e-f1f6-4e8b-a53b-8fd1e34ce3ca): Finish ensure networks exist, duration 0.04 seconds
Aug  3 04:48:26 sau-2d4a1-or Returning API error: 500, server error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 116, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 688, in post
        return self._instance_start(instance_uuid, instance, network, namespace, placed_on)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 733, in _instance_start
        return self._instance_start_local(instance_uuid, instance, network, namespace)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 829, in _instance_start_local
        n.ensure_mesh()
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 366, in ensure_mesh
        discovered = list(self.discover_mesh())
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 330, in discover_mesh
        shell=True)
      File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 434, in execute
        cmd=sanitized_cmd)
    oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
    Command: bridge fdb show brport vxlan-8
    Exit code: 255
    Stdout: ''
    Stderr: 'Cannot find device "vxlan-8"\n'

```
