### ISSUE TITLE
DHCP bug and missing exception

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#316]
Coming back to this after escaping current rabbit hole
```
Sep  9 11:23:56 sf-1 sf-net: INFO network(8dfcc174-d66e-47f6-8f2d-bb17158aa113, vxid 3): Finish enable nat, duration 0.47 seconds
Sep  9 11:23:56 sf-1 sf-net: INFO network(8dfcc174-d66e-47f6-8f2d-bb17158aa113, vxid 3): Adding new mesh element 192.168.72.201
Sep  9 11:23:56 sf-1 sf-net: INFO 8dfcc174-d66e-47f6-8f2d-bb17158aa113: net.from_db() network is state=deleted
Sep  9 11:23:56 sf-1 sf-net: INFO network(8dfcc174-d66e-47f6-8f2d-bb17158aa113, vxid 3): Finish update dhcp, duration 0.04 seconds
Sep  9 11:23:56 sf-1 sh[14046]: Traceback (most recent call last):
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 157, in run
Sep  9 11:23:56 sf-1 sh[14046]:     self._maintain_networks()
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 65, in _maintain_networks
Sep  9 11:23:56 sf-1 sh[14046]:     n.create()
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 197, in create
Sep  9 11:23:56 sf-1 sh[14046]:     self.update_dhcp()
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 315, in update_dhcp
Sep  9 11:23:56 sf-1 sh[14046]:     d = dhcp.DHCP(self.uuid, subst['vx_veth_inner'])
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/dhcp.py", line 29, in __init__
Sep  9 11:23:56 sf-1 sh[14046]:     'router': n.router,
Sep  9 11:23:56 sf-1 sh[14046]: AttributeError: 'NoneType' object has no attribute 'router'
Sep  9 11:23:56 sf-1 sh[14046]: During handling of the above exception, another exception occurred:
Sep  9 11:23:56 sf-1 sh[14046]: Traceback (most recent call last):
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Sep  9 11:23:56 sf-1 sh[14046]:     sys.exit(main())
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 174, in main
Sep  9 11:23:56 sf-1 sh[14046]:     _audit_daemons()
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 167, in _audit_daemons
Sep  9 11:23:56 sf-1 sh[14046]:     _start_daemon(d)
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 154, in _start_daemon
Sep  9 11:23:56 sf-1 sh[14046]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Sep  9 11:23:56 sf-1 sh[14046]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 160, in run
Sep  9 11:23:56 sf-1 sh[14046]:     except exceptions.ConnectionFailedError:
Sep  9 11:23:56 sf-1 sh[14046]: AttributeError: module 'shakenfist.exceptions' has no attribute 'ConnectionFailedError'
```

**Comment by mikalstill** [comment]
Fixed. The deleted-network `NoneType.router` crash can no longer occur: the dnsmasq update path loads the network via `Network.from_db` and raises `NoSuchNetwork` if it is gone (`shakenfist/operations/net_op.py:104-107`), and `exceptions.ConnectionFailedError` no longer exists anywhere in the tree.

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
