### ISSUE TITLE
Continued issues with setting non-string configuration values

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#337]
```
Sep 30 05:56:14 sf-localhost Returning API error: 400, unsupported operand type(s) for -: 'int' and 'str'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 116, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 687, in post
        return self._instance_start(instance_uuid, instance, network, namespace, placed_on)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 696, in _instance_start
        candidates = SCHEDULER.place_instance(instance, network)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/scheduler.py", line 178, in place_instance
        if not self._has_sufficient_ram(instance.db_entry['memory'], node):
      File "/usr/local/lib/python3.6/dist-packages/shakenfist/scheduler.py", line 53, in _has_sufficient_ram
        (config.parsed.get('RAM_SYSTEM_RESERVATION') * 1024))
    TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

**Comment by mikalstill** [comment]
Sigh. I was using the wrong version of the code, ignore me.
