### ISSUE TITLE
Traceback in CI logs

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#351]
```
Oct  6 09:41:20 sfci-6xrazj sh[23338]: Traceback (most recent call last):
Oct  6 09:41:20 sfci-6xrazj sh[23338]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/logutil.py", line 129, in withObj
Oct  6 09:41:20 sfci-6xrazj sh[23338]:     label, value = object.unique_label()
Oct  6 09:41:20 sfci-6xrazj sh[23338]: AttributeError: 'str' object has no attribute 'unique_label'
Oct  6 09:41:20 sfci-6xrazj sh[23338]: During handling of the above exception, another exception occurred:
Oct  6 09:41:20 sfci-6xrazj sh[23338]: Traceback (most recent call last):
Oct  6 09:41:20 sfci-6xrazj sh[23338]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Oct  6 09:41:20 sfci-6xrazj sh[23338]:     sys.exit(main())
Oct  6 09:41:20 sfci-6xrazj sh[23338]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 146, in main
Oct  6 09:41:20 sfci-6xrazj sh[23338]:     'iptables -t nat -A POSTROUTING -o %(physical_nic)s -j MASQUERADE' % subst)
Oct  6 09:41:20 sfci-6xrazj sh[23338]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 40, in __exit__
Oct  6 09:41:20 sfci-6xrazj sh[23338]:     LOG.withObj(self.object).info(
Oct  6 09:41:20 sfci-6xrazj sh[23338]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/logutil.py", line 131, in withObj
Oct  6 09:41:20 sfci-6xrazj sh[23338]:     raise Exception('Bad object - no unique_label() function')
Oct  6 09:41:20 sfci-6xrazj sh[23338]: Exception: Bad object - no unique_label() function
```

**Comment by mikalstill** [comment]
I think this is happening because self.object in the calling RecordedOperation is None, but I am unclear why the current code isn't handling that sensibly.

**Comment by mandoonandy** [comment]
Damn a single instance of a str in a RecordedOperation - during start up.

Standby for a fix.
