### ISSUE TITLE
Network has no ipblock

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#359]
Another issue from CI:

```
Oct  7 06:51:43 sfci-lxayws sh[21926]: Traceback (most recent call last):
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Oct  7 06:51:43 sfci-lxayws sh[21926]:     sys.exit(main())
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 163, in main
Oct  7 06:51:43 sfci-lxayws sh[21926]:     _audit_daemons()
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 156, in _audit_daemons
Oct  7 06:51:43 sfci-lxayws sh[21926]:     _start_daemon(d)
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 100, in _start_daemon
Oct  7 06:51:43 sfci-lxayws sh[21926]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 141, in run
Oct  7 06:51:43 sfci-lxayws sh[21926]:     self._process_network_node_workitems()
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 116, in _process_network_node_workitems
Oct  7 06:51:43 sfci-lxayws sh[21926]:     n.create()
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 122, in create
Oct  7 06:51:43 sfci-lxayws sh[21926]:     subst = self.subst_dict()
Oct  7 06:51:43 sfci-lxayws sh[21926]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 88, in subst_dict
Oct  7 06:51:43 sfci-lxayws sh[21926]:     'ipblock': self.ipblock,
Oct  7 06:51:43 sfci-lxayws sh[21926]: AttributeError: 'Network' object has no attribute 'ipblock'
```

**Comment by mikalstill** [comment]
Its odd, the code shouldn't let this happen (self.ipblock is initialised in __init__).

**Comment by mikalstill** [comment]
This hasn't been seen for a while. Closing.
