### ISSUE TITLE
Libvirt appears to be treating our instance UUID as a libvirt UUID

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#368]
They're different...

```
Oct  7 21:31:43 sfci-tpcecl sh[22086]: libvirt: QEMU Driver error : Domain not found: no domain with matching uuid '308c120d-ac56-4535-a7dd-d90f006c7b8a' (sf:308c120d-ac56-4535-a7dd-d90f006c7b8a)
Oct  7 21:31:43 sfci-tpcecl sh[22086]: libvirt: QEMU Driver error : Domain not found: no domain with matching uuid '308c120d-ac56-4535-a7dd-d90f006c7b8a' (sf:308c120d-ac56-4535-a7dd-d90f006c7b8a)
Oct  7 21:31:43 sfci-tpcecl INFO sf-queues-1602106288.1677623-000[31368] Finish delete netns; duration=0.009617328643798828; network=eedfe72d-a15c-4cb5-ad69-3965c0333d13
Oct  7 21:31:43 sfci-tpcecl ERROR sf-resources[22167] [Exception] Ignored error in resource statistics: Domain not found: no domain with matching uuid '308c120d-ac56-4535-a7dd-d90f006c7b8a' (sf:308c120d-ac56-4535-a7dd-d90f006c7b8a)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 171, in run
    update_metrics()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 155, in update_metrics
    stats = _get_stats()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 102, in _get_stats
    _, maxmem, mem, cpus, cpu_time = guest.info()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1320, in info
    if ret is None: raise libvirtError ('virDomainGetInfo() failed', dom=self)
libvirt.libvirtError: Domain not found: no domain with matching uuid '308c120d-ac56-4535-a7dd-d90f006c7b8a' (sf:308c120d-ac56-4535-a7dd-d90f006c7b8a)
```

This instance had already been deleted, so this might be a race condition? https://jenkins.shakenfist.com/job/shakenfist/job/stabilise-ci/11/execution/node/28/log/?consoleFull is the relevant log.

**Comment by mikalstill** [comment]
Haven't seen this one in ages.
