### ISSUE TITLE
Always use locally administered mac addresses

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#409]
```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/workspace/shakenfist_bug-359/deploy/shakenfist_ci/tests/test_console_log.py", line 35, in test_console_log
    self._await_login_prompt(inst['uuid'])

      File "/tmp/workspace/shakenfist_bug-359/deploy/shakenfist_ci/base.py", line 89, in _await_login_prompt
    instance_uuid, 'trigger', 'login prompt', after)

      File "/tmp/workspace/shakenfist_bug-359/deploy/shakenfist_ci/base.py", line 105, in _await_event
    % instance_uuid)

    shakenfist_ci.base.TimeoutException: Instance f351823e-7c59-47bb-b52e-ef1f04cf5635 was not created in a reasonable time
```

**Comment by mikalstill** [comment]
```
# sf-client --simple instance events f351823e-7c59-47bb-b52e-ef1f04cf5635 
timestamp,node,operation,phase,duration,message
2020-10-16 02:28:57.472732,sfci-sbuupa.c.mikal-269605.internal,uuid allocated,None,None,None
2020-10-16 02:28:57.544904,sfci-sbuupa.c.mikal-269605.internal,schedule,start,None,None
2020-10-16 02:28:57.548692,sfci-sbuupa.c.mikal-269605.internal,schedule,Initial candidates,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.550981,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough actual CPU,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.553257,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle CPU,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.555352,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle RAM,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.557670,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle disk,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.573028,sfci-sbuupa.c.mikal-269605.internal,schedule,Have most matching networks,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.577469,sfci-sbuupa.c.mikal-269605.internal,schedule,Have most matching images,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.581883,sfci-sbuupa.c.mikal-269605.internal,schedule,finish,0.036978960037231445,None
2020-10-16 02:28:57.586654,sfci-sbuupa.c.mikal-269605.internal,placement,None,None,sfci-sbuupa.c.mikal-269605.internal
2020-10-16 02:28:57.598689,sfci-sbuupa.c.mikal-269605.internal,create,enqueued,None,None
2020-10-16 02:28:57.745769,sfci-sbuupa.c.mikal-269605.internal,instance preflight,dequeued,None,Work item 1602815337.5924563-000
2020-10-16 02:28:57.756241,sfci-sbuupa.c.mikal-269605.internal,state changed,initial -> preflight,None,None
2020-10-16 02:28:57.764932,sfci-sbuupa.c.mikal-269605.internal,schedule,start,None,None
2020-10-16 02:28:57.767154,sfci-sbuupa.c.mikal-269605.internal,schedule,Forced candidates,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.769412,sfci-sbuupa.c.mikal-269605.internal,schedule,Initial candidates,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.771952,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough actual CPU,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.774125,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle CPU,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.776283,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle RAM,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.778657,sfci-sbuupa.c.mikal-269605.internal,schedule,Have enough idle disk,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.795360,sfci-sbuupa.c.mikal-269605.internal,schedule,Have most matching networks,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.801394,sfci-sbuupa.c.mikal-269605.internal,schedule,Have most matching images,None,['sfci-sbuupa.c.mikal-269605.internal']
2020-10-16 02:28:57.806582,sfci-sbuupa.c.mikal-269605.internal,schedule,finish,0.04165935516357422,None
2020-10-16 02:28:58.308205,sfci-sbuupa.c.mikal-269605.internal,instance start,dequeued,None,Work item 1602815337.5924563-000
2020-10-16 02:28:58.329784,sfci-sbuupa.c.mikal-269605.internal,ensure networks exist,start,None,None
2020-10-16 02:28:58.905524,sfci-sbuupa.c.mikal-269605.internal,ensure networks exist,finish,0.575735330581665,None
2020-10-16 02:28:58.907979,sfci-sbuupa.c.mikal-269605.internal,instance creation,start,None,None
2020-10-16 02:28:58.916452,sfci-sbuupa.c.mikal-269605.internal,state changed,preflight -> creating,None,None
2020-10-16 02:28:58.919117,sfci-sbuupa.c.mikal-269605.internal,make config drive,start,None,None
2020-10-16 02:28:58.943968,sfci-sbuupa.c.mikal-269605.internal,make config drive,finish,0.024848222732543945,None
2020-10-16 02:29:00.067729,sfci-sbuupa.c.mikal-269605.internal,fetch image,start,None,None
2020-10-16 02:29:00.423871,sfci-sbuupa.c.mikal-269605.internal,fetch image,finish,0.3561410903930664,None
2020-10-16 02:29:00.426795,sfci-sbuupa.c.mikal-269605.internal,transcode image,start,None,None
2020-10-16 02:29:00.429042,sfci-sbuupa.c.mikal-269605.internal,transcode image,finish,0.0022459030151367188,None
2020-10-16 02:29:00.435069,sfci-sbuupa.c.mikal-269605.internal,detect cdrom images,start,None,None
2020-10-16 02:29:00.438021,sfci-sbuupa.c.mikal-269605.internal,detect cdrom images,finish,0.0029511451721191406,None
2020-10-16 02:29:00.440394,sfci-sbuupa.c.mikal-269605.internal,resize image,start,None,None
2020-10-16 02:29:00.443130,sfci-sbuupa.c.mikal-269605.internal,resize image,finish,0.002733469009399414,None
2020-10-16 02:29:00.445903,sfci-sbuupa.c.mikal-269605.internal,create copy on write layer,start,None,None
2020-10-16 02:29:00.682688,sfci-sbuupa.c.mikal-269605.internal,create copy on write layer,finish,0.23675131797790527,None
2020-10-16 02:29:00.691815,sfci-sbuupa.c.mikal-269605.internal,create domain XML,start,None,None
2020-10-16 02:29:00.716808,sfci-sbuupa.c.mikal-269605.internal,create domain XML,finish,0.024989604949951172,None
2020-10-16 02:29:00.719132,sfci-sbuupa.c.mikal-269605.internal,create domain,start,None,None
2020-10-16 02:29:58.309327,sfci-sbuupa.c.mikal-269605.internal,detected poweroff,complete,None,None
2020-10-16 02:36:33.866680,sfci-sbuupa.c.mikal-269605.internal,instance delete,dequeued,None,Work item 1602815793.6908944-000
2020-10-16 02:36:38.901199,sfci-sbuupa.c.mikal-269605.internal,lock,acquire,None,Waiting for lock more than threshold
2020-10-16 02:38:34.536921,sfci-sbuupa.c.mikal-269605.internal,lock,failed,None,Failed to acquire lock after 120.67 seconds
2020-10-16 02:38:34.542279,sfci-sbuupa.c.mikal-269605.internal,lock,acquired,None,Waited 120 seconds for lock
2020-10-16 02:38:34.553635,sfci-sbuupa.c.mikal-269605.internal,tasks complete,dequeued,None,Work item 1602815793.6908944-000
2020-10-16 02:38:37.378514,sfci-sbuupa.c.mikal-269605.internal,create domain,finish,576.6593773365021,None
2020-10-16 02:38:37.388305,sfci-sbuupa.c.mikal-269605.internal,state changed,creating -> created,None,None
2020-10-16 02:38:37.390695,sfci-sbuupa.c.mikal-269605.internal,instance creation,finish,578.4827120304108,None
2020-10-16 02:38:38.152850,sfci-sbuupa.c.mikal-269605.internal,trigger monitor,started,None,None
2020-10-16 02:38:38.428999,sfci-sbuupa.c.mikal-269605.internal,tasks complete,dequeued,None,Work item 1602815337.5924563-000
```

**Comment by mikalstill** [comment]
* 2020-10-16 02:28:57.472732: uuid allocated
* 2020-10-16 02:28:57.598689: instance create queued
* 2020-10-16 02:28:58.308205: instance create dequeued
* 2020-10-16 02:29:00.719132: create domain
* 2020-10-16 02:29:58.309327: detected poweroff
* 2020-10-16 02:36:33.866680: instance delete
* 2020-10-16 02:38:37.388305: creating -> created

**Comment by mikalstill** [comment]
That delete in the middle was an API request (test timing out):

```
Oct 16 02:36:33 sfci-sbuupa INFO gunicorn: worker [sf-api][32383] API request: DELETE http://localhost:13000/instances/f351823e-7c59-47bb-b52e-ef1f04cf5635
```

**Comment by mikalstill** [comment]
Instance was failing to power on...

```
# grep f351823e-7c59-47bb-b52e-ef1f04cf5635 /var/log/syslog | grep -i "power" | sed 's/.*sf-queues/sf-queues/' | uniq -c
     10 sf-queues-1602815337.5924563-000[5316] Instance required an additional attempt to power on; instance=f351823e-7c59-47bb-b52e-ef1f04cf5635
      1 Oct 16 02:29:58 sfci-sbuupa INFO sf-cleaner[32305] Detected power off for instance; instance=f351823e-7c59-47bb-b52e-ef1f04cf5635
     90 sf-queues-1602815337.5924563-000[5316] Instance required an additional attempt to power on; instance=f351823e-7c59-47bb-b52e-ef1f04cf5635
      1 sf-queues-1602815337.5924563-000[5316] Instance now powered on; instance=f351823e-7c59-47bb-b52e-ef1f04cf5635
```

**Comment by mikalstill** [comment]
That is, it took 100 attempts to get the instance to power on.

**Comment by mikalstill** [comment]
```/var/log/libvirt/qemu/sf:f351823e-7c59-47bb-b52e-ef1f04cf5635.log``` says "2020-10-16 02:30:20.193+0000: shutting down, reason=failed" a lot, which leads me to find this:

```
Oct 16 02:30:20 sfci-sbuupa libvirtd[26115]: 2020-10-16 02:30:20.161+0000: 26131: error : virNetDevTapCreateInBridgePort:649 : unsupported configuration: Unable to use MAC address starting with reserved value 0xFE - 'fe:86:c8:56:b7:f7' -
```

**Comment by mikalstill** [comment]
randmac hates me:

```
>>> while True:
...     possible_mac = str(randmac.RandMac(
...                 '02:00:00:00:00:00', False)).lstrip('\'').rstrip('\'')
...     print(possible_mac)
...     time.sleep(1)
... 
12:9f:6c:be:0c:c7
e2:ff:3e:3b:6e:60
d2:3a:d6:af:1d:c7
6a:3e:87:da:00:e5
9e:5d:50:aa:3f:10
26:cc:f4:f0:1f:ca
1e:ee:b1:77:3e:d2
8e:bc:11:87:9e:c5
a2:56:59:a2:af:24
06:5e:08:79:af:c9
06:32:a8:0f:34:f6
ce:6e:6b:39:59:89
ba:f8:b7:9d:8f:29
4e:f6:9b:b9:a5:ca
```
