### ISSUE TITLE
Rare CI error: IO error for snapshot creation

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#430]
```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/tmp/workspace/shakenfist_bug-428/deploy/shakenfist_ci/tests/test_snapshots.py", line 82, in test_multiple_disk_snapshots
    snap1 = self.test_client.snapshot_instance(inst['uuid'])
      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 225, in snapshot_instance
    '/snapshot', data={'all': all})
      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 152, in _request_url
    return self._actual_request_url(method, url, data=data)
      File "/usr/local/lib/python3.6/dist-packages/shakenfist_client/apiclient.py", line 127, in _actual_request_url
    'API request failed', method, url, r.status_code, r.text)
    shakenfist_client.apiclient.InternalServerError: ('API request failed', 'POST', 'http://localhost:13000/instances/6055a3ea-0b08-4bdc-9f5b-333958a6b392/snapshot', 500, '{"error": "server error: ProcessExecutionError(\'\', \'qemu-img: error while reading sector 62976: Input/output error\\\\n\', 1, \'qemu-img convert --force-share -O qcow2 /srv/shakenfist/instances/6055a3ea-0b08-4bdc-9f5b-333958a6b392/vda /srv/shakenfist/snapshots/f1889ee8-4d58-4280-94cb-49066e39021a/vda\', None)", "status": 500}')
```

We should at least catch the error I suppose. Seen once in CI.

**Comment by mikalstill** [comment]
I haven't seen this in ages. Closing.
