### ISSUE TITLE
Ensure network is created before updating DHCP

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#438]
```
Oct 21 05:35:38 syd-sf-1 sh[2941]: Traceback (most recent call last):
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Oct 21 05:35:38 syd-sf-1 sh[2941]:     sys.exit(main())
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 165, in main
Oct 21 05:35:38 syd-sf-1 sh[2941]:     _audit_daemons()
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 158, in _audit_daemons
Oct 21 05:35:38 syd-sf-1 sh[2941]:     _start_daemon(d)
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 102, in _start_daemon
Oct 21 05:35:38 syd-sf-1 sh[2941]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/net.py", line 151, in run
Oct 21 05:35:38 syd-sf-1 sh[2941]:     self._process_network_node_workitems()
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/net.py", line 132, in _process_network_node_workitems
Oct 21 05:35:38 syd-sf-1 sh[2941]:     n.update_dhcp()
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 282, in update_dhcp
Oct 21 05:35:38 syd-sf-1 sh[2941]:     self.ensure_mesh()
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 348, in ensure_mesh
Oct 21 05:35:38 syd-sf-1 sh[2941]:     discovered = list(self.discover_mesh())
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 310, in discover_mesh
Oct 21 05:35:38 syd-sf-1 sh[2941]:     stdout, _ = util.execute(
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/util.py", line 281, in execute
Oct 21 05:35:38 syd-sf-1 sh[2941]:     return processutils.execute(
Oct 21 05:35:38 syd-sf-1 sh[2941]:   File "/usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py", line 431, in execute
Oct 21 05:35:38 syd-sf-1 sh[2941]:     raise ProcessExecutionError(exit_code=_returncode,
Oct 21 05:35:38 syd-sf-1 sh[2941]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Oct 21 05:35:38 syd-sf-1 sh[2941]: Command: bridge fdb show brport vxlan-2
Oct 21 05:35:38 syd-sf-1 sh[2941]: Exit code: 255
Oct 21 05:35:38 syd-sf-1 sh[2941]: Stdout: ''
Oct 21 05:35:38 syd-sf-1 sh[2941]: Stderr: 'Cannot find device "vxlan-2"\n'
```

Looking at the timestamps, this happened before the network was actually setup. We need to wait a bit before we start checking.

**Comment by mikalstill** [comment]
Oh, this is in the network node queue. It looks like the UpdateDHCPNetworkTask landed before the DeployNetworkTask?
