### ISSUE TITLE
Ignored exceptions in sf-queues from CI

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#470]
```
Oct 26 01:43:48 sfci-vzt6wj ERROR sf-resources[32741] [Exception] Ignored error in resource statistics: Domain not found: no domain with matching uuid '0809b8fc-d1ee-4554-b5b2-e0b8b0f5d018' (sf:0809b8fc-d1ee-4554-b5b2-e0b8b0f5d018)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 179, in run
    update_metrics()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 155, in update_metrics
    stats = _get_stats()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/resources.py", line 102, in _get_stats
    _, maxmem, mem, cpus, cpu_time = guest.info()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1320, in info
    if ret is None: raise libvirtError ('virDomainGetInfo() failed', dom=self)
libvirt.libvirtError: Domain not found: no domain with matching uuid '0809b8fc-d1ee-4554-b5b2-e0b8b0f5d018' (sf:0809b8fc-d1ee-4554-b5b2-e0b8b0f5d018)
```

This sets off our "no tracebacks in logs" bogo filter in CI.

**Comment by mikalstill** [comment]
We don't see this any more.
