### ISSUE TITLE
Should errors in performing network node tasks put instances on that network into an error state?

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#520]
If we know the network is broken, then don't we also know the instances are broken? My specific example is this:

```
Nov  3 09:01:38 cbr-sf-1 INFO sf-net[804692] Finish enable virtual routing; duration=0.033017635345458984; network=8a451510-0c58-48f9-9a51-bbc50da885d4
Nov  3 09:01:38 cbr-sf-1 sh[804692]: Traceback (most recent call last):
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     sys.exit(main())
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 181, in main
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     _audit_daemons()
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 161, in _audit_daemons
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     _start_daemon(d)
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 102, in _start_daemon
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/net.py", line 170, in run
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     self._maintain_networks()
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/net.py", line 67, in _maintain_networks
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     n.create()
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 209, in create
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     self.deploy_nat()
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 245, in deploy_nat
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     util.execute(None,
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/util.py", line 283, in execute
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     return processutils.execute(
Nov  3 09:01:38 cbr-sf-1 sh[804692]:   File "/usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py", line 431, in execute
Nov  3 09:01:38 cbr-sf-1 sh[804692]:     raise ProcessExecutionError(exit_code=_returncode,
Nov  3 09:01:38 cbr-sf-1 sh[804692]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Nov  3 09:01:38 cbr-sf-1 sh[804692]: Command: ip netns exec 8a451510-0c58-48f9-9a51-bbc50da885d4 ip addr add 192.168.20.95/255.255.255.0 dev phy-1-i
Nov  3 09:01:38 cbr-sf-1 sh[804692]: Exit code: 1
Nov  3 09:01:38 cbr-sf-1 sh[804692]: Stdout: ''
Nov  3 09:01:38 cbr-sf-1 sh[804692]: Stderr: 'Cannot find device "phy-1-i"\n'
Nov  3 09:01:47 cbr-sf-1 WARNING sf-main[786454] net died (pid 804692)
```

Should probably mark the network in question as dead and therefore the instances on it.

**Comment by mandoonandy** [comment]
Yes, the instance does need some action. I'm not sure killing the instance is warranted since it may contain data that could be extracted via a still working network connection or to disk.

Which code version caused this? I am surprised/disappointed that it is still happening.

**Comment by mikalstill** [comment]
I think this was caused by me doing dark evil things with glusterfs, but regardless I think we should handle this general failure case as a "worst case". You could extract data as a snapshot at this point, but I do think we should highlight that the network is broken. How about a new instance state of "broken network" then?

**Comment by mandoonandy** [comment]
Sounds good. Maybe set the state to something like `problem`. The network may not be broken for that instance, this could be a problem on another node. We can then put something in the instance event log?
