### ISSUE TITLE
Error in CI: ip link add phy-5-o ... --> RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#532]
```
Nov 11 09:36:29 sfci-ogma4d INFO sf-queues-1605087388.455102-000[18665] Finish ensure networks exist; duration=0.25678586959838867; instance=887037b6-9cbf-4ed3-b87f-2cf31585615f
Nov 11 09:36:29 localhost gunicorn.sf.access: [9737] 127.0.0.1 - - [11/Nov/2020:09:36:29 +0000] "POST /auth HTTP/1.1" 200 298 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Nov 11 09:36:29 sfci-ogma4d ERROR sf-queues-1605087388.455102-000[18665] [Exception] Ignored error in sf-queues: Unexpected error while running command.
Command: ip link add phy-5-o type veth peer name phy-5-i
Exit code: 2
Stdout: ''
Stderr: 'RTNETLINK answers: File exists\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/queues.py", line 82, in handle
    instance_start(instance_uuid, task.network())
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/queues.py", line 229, in instance_start
    n.create()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 198, in create
    'peer name %(physical_veth_inner)s' % subst)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 144, in create_interface
    'extra': extra})
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 285, in execute
    env_variables=env_variables, shell=True)
  File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 441, in execute
    cmd=sanitized_cmd)
oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Command: ip link add phy-5-o type veth peer name phy-5-i
Exit code: 2
Stdout: ''
Stderr: 'RTNETLINK answers: File exists\n'
Nov 11 09:36:29 sfci-ogma4d INFO gunicorn: worker [sf-api][9737] API request: GET http://localhost:13000/auth/namespaces
    Args: ()
    KWargs: {}
Nov 11 09:36:29 localhost gunicorn.sf.access: [9737] 127.0.0.1 - - [11/Nov/2020:09:36:29 +0000] "GET /auth/namespaces HTTP/1.1" 200 60 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) Shaken Fist/0.0.1"
Nov 11 09:36:29 sfci-ogma4d INFO gunicorn: worker [sf-api][9737] API request: POST http://localhost:13000/auth/namespaces
    Args: ()
    KWargs: {'namespace': 'ci-placement-iiwocruv'}
Nov 11 09:36:29 sfci-ogma4d INFO sf-queues-1605087388.455102-000[18665] Enqueued workitem; jobname=1605087389.4877782-000; queuename=sfci-ogma4d.c.mikal-269605.internal; workitem={'tasks': [QueueTask:ErrorInstanceTask: {'task': 'instance_error', 'version': 1, 'instance_uuid': '887037b6-9cbf-4ed3-b87f-2cf31585615f', 'network': [], 'error_msg': "failed queue task: Unexpected error while running command.\nCommand: ip link add phy-5-o type veth peer name phy-5-i\nExit code: 2\nStdout: ''\nStderr: 'RTNETLINK answers: File exists\\n'"}]}
```

**Comment by mikalstill** [comment]
Another network race? From https://jenkins.shakenfist.com/job/shakenfist/view/change-requests/job/PR-531/4/consoleFull

**Comment by mikalstill** [comment]
I think this is fixed now (in develop that is).
