### ISSUE TITLE
Instances failing to start if size is passed as a string (which client-python does)

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#536]
This command line:

```
sf-client instance create disk-thing 1 1024 \
    -D size=8,base=cirros,bus=ide,type=disk \
    -D size=16,type=disk \
    -D base=http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso
```

Causes this exception:

```
Nov 12 07:00:33 syd-sf-3 ERROR sf-queues-1605164279.3725202-000[1529097] [Exception] Ignored error in sf-queues: %d format: a number is required, not str
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/queues.py", line 82, in handle
    instance_start(instance_uuid, task.network())
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/queues.py", line 241, in instance_start
    instance.create(lock=lock)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/virt.py", line 196, in create
    images.create_cow([lock], hashed_image_path,
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/images.py", line 331, in create_cow
    'qemu-img create -b %s -f qcow2 %s %dG'
TypeError: %d format: a number is required, not str
```

**Comment by mikalstill** [comment]
This command line is sufficient to cause the error:

```
sf-client instance create disk-thing 1 1024 -D size=8,base=cirros,bus=ide,type=disk
```

**Comment by mikalstill** [comment]
API request seems to be parsed correctly, except the client passes the size as a string not an int.

```
Nov 12 07:06:53 syd-sf-1 INFO gunicorn: worker [sf-api][628540] API request: POST http://localhost:13000/instances
    Args: ()
    KWargs: {'name': 'disk-thing', 'cpus': 1, 'memory': 1024, 'network': [], 'disk': [{'size': '8', 'base': 'cirros', 'bus': 'ide', 'type': 'disk'}], 'ssh_key': None, 'user_data': None, 'namespace': None, 'video': 
{'model': 'cirrus', 'memory': 16384}}
```
