### ISSUE TITLE
Events lookup fails

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#54]
```Jun 17 14:43:02 sf-1 sf[20328]: ERROR:shakenfist.daemons.external_api:Exception on /instances/6012856d-ae34-4908-8660-242149311cc8/events [GET]
Jun 17 14:43:02 sf-1 sf[20328]: Traceback (most recent call last):
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
Jun 17 14:43:02 sf-1 sf[20328]:     rv = self.dispatch_request()
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
Jun 17 14:43:02 sf-1 sf[20328]:     return self.view_functions[rule.endpoint](**req.view_args)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 472, in wrapper
Jun 17 14:43:02 sf-1 sf[20328]:     return self.make_response(data, code, headers=headers)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 501, in make_response
Jun 17 14:43:02 sf-1 sf[20328]:     resp = self.representations[mediatype](data, *args, **kwargs)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/local/lib/python3.6/dist-packages/flask_restful/representations/json.py", line 21, in output_json
Jun 17 14:43:02 sf-1 sf[20328]:     dumped = dumps(data, **settings) + "\n"
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Jun 17 14:43:02 sf-1 sf[20328]:     return _default_encoder.encode(obj)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Jun 17 14:43:02 sf-1 sf[20328]:     chunks = self.iterencode(o, _one_shot=True)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Jun 17 14:43:02 sf-1 sf[20328]:     return _iterencode(o, 0)
Jun 17 14:43:02 sf-1 sf[20328]:   File "/usr/lib/python3.6/json/encoder.py", line 180, in default
Jun 17 14:43:02 sf-1 sf[20328]:     o.__class__.__name__)
Jun 17 14:43:02 sf-1 sf[20328]: TypeError: Object of type 'generator' is not JSON serializable
```

**Comment by mikalstill** [comment]
I think I just need to wrap the DB call in a list() here.
