### ISSUE TITLE
Network traceback in unrelated CI runs

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#555]
```
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: Traceback (most recent call last):
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     sys.exit(main())
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 168, in main
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     _audit_daemons()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 161, in _audit_daemons
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     _start_daemon(d)
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 102, in _start_daemon
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 164, in run
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     self._process_network_node_workitems()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 130, in _process_network_node_workitems
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     n.create()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 210, in create
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     self.update_dhcp()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 342, in update_dhcp
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     d.restart_dhcpd()
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/dhcp.py", line 111, in restart_dhcpd
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     '%(in_netns)s dnsmasq --conf-file=%(config_dir)s/config' % self.subst)
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 285, in execute
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     env_variables=env_variables, shell=True)
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:   File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 441, in execute
Nov 24 10:06:40 sfci-ilk4dg sh[24540]:     cmd=sanitized_cmd)
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: Command: ip netns exec b3fb6bb8-e953-414e-b712-2de5b46edea7 dnsmasq --conf-file=/srv/shakenfist/dhcp/b3fb6bb8-e953-414e-b712-2de5b46edea7/config
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: Exit code: 1
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: Stdout: ''
Nov 24 10:06:40 sfci-ilk4dg sh[24540]: Stderr: 'Cannot open network namespace "b3fb6bb8-e953-414e-b712-2de5b46edea7": No such file or directory\n'
```

This is from https://jenkins.shakenfist.com/job/shakenfist/view/change-requests/job/PR-553/1/execution/node/33/log/?consoleFull

**Comment by mikalstill** [comment]
This hasn't been seen in a while.
