### ISSUE TITLE
We don't sufficiently validate netblocks when creating networks

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#569]
```
Nov 30 07:22:59 cbr-sf-1 INFO gunicorn: worker [sf-api][3613923] API request: POST http://sf-1:13000/instances
    Args: ()
    KWargs: {'name': 'ubuntu', 'cpus': 2, 'memory': 2048, 'network': [{'network_uuid': '3edb03de-4f3d-4859-b822-94924073a1ea', 'address': None, 'macaddress': None, 'm
odel': 'virtio'}], 'ssh_key': None, 'user_data': None, 'namespace': 'nstest', 'video': {'model': 'cirrus', 'memory': 16384}, 'disk': [{'size': 20, 'base': 'ubuntu', '
bus': None, 'type': 'disk'}]}
Nov 30 07:22:59 cbr-sf-1 INFO gunicorn: worker [sf-api][3613923] Added event; duration=None; fqdn=sf-1; instance=2e90e01e-d48e-4d6d-8932-3b68125c2fce; message=None; o
peration=uuid allocated; phase=None
Nov 30 07:22:59 cbr-sf-1 ERROR gunicorn: worker [sf-api][3613923] Server error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/external_api/app.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/external_api/app.py", line 697, in post
    n = net.from_db(netdesc['network_uuid'])
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 36, in from_db
    return Network(dbnet)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/net.py", line 51, in __init__
    self.router = ipm.get_address_at_index(1)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist/ipmanager.py", line 29, in get_address_at_index
    return self.ipblock_obj[idx]
  File "/usr/lib/python3.8/ipaddress.py", line 659, in __getitem__
    raise IndexError('address out of range')
IndexError: address out of range
```

**Comment by mikalstill** [comment]
Oh, typo in the netblock?

```
$ sf-client network show 3edb03de-4f3d-4859-b822-94924073a1ea
uuid            : 3edb03de-4f3d-4859-b822-94924073a1ea
name            : nsnet
vxlan id        : 2
netblock        : 192.168.20.024
provide dhcp    : True
provide nat     : True
floating gateway: None
namespace       : nstest
state           : created

Metadata:
```

**Comment by mikalstill** [comment]
This should have errored:

```
sf-client network create nsnet 192.168.20.024 --namespace nstest
```

**Comment by mikalstill** [comment]
I can't delete it either:

```
$ sf-client network list
+--------------------------------------+---------+-----------+----------------+
|                 uuid                 |   name  | namespace |    netblock    |
+--------------------------------------+---------+-----------+----------------+
| 30acadd4-66ee-4390-9477-e31d11fe44cb | testnet |   system  | 192.16.10.0/24 |
| 3edb03de-4f3d-4859-b822-94924073a1ea |  nsnet  |   nstest  | 192.168.20.024 |
+--------------------------------------+---------+-----------+----------------+
cloudadmin@cbr-sf-1:~$ sf-client network delete 3edb03de-4f3d-4859-b822-94924073a1ea
ERROR: Internal Server Error: {"error": "server error: IndexError('address out of range')", "status": 500}
```

**Comment by mikalstill** [comment]
This breaks the network daemon, as below:

```
Dec  4 07:47:51 sfci-kwm39c sh[2959]: Traceback (most recent call last):
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     sys.exit(main())
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 169, in main
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     _audit_daemons()
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 162, in _audit_daemons
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     _start_daemon(d)
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 103, in _start_daemon
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 178, in run
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     self._maintain_networks()
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 63, in _maintain_networks
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     n = net.Network.from_db(network)
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 125, in from_db
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     ipm = IPManager.from_db(uuid)
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/ipmanager.py", line 41, in from_db
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     ipm = IPManager(uuid=uuid, **db_data['ipmanager.v1'])
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/ipmanager.py", line 11, in __init__
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     self.ipblock_obj = ipaddress.ip_network(ipblock, strict=False)
Dec  4 07:47:51 sfci-kwm39c sh[2959]:   File "/usr/lib/python3.6/ipaddress.py", line 84, in ip_network
Dec  4 07:47:51 sfci-kwm39c sh[2959]:     address)
Dec  4 07:47:51 sfci-kwm39c sh[2959]: ValueError: '192.168.20.024' does not appear to be an IPv4 or IPv6 network
```
