### ISSUE TITLE
Frequent single node CI failures for missing physical interfaces

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#577]
We see this a lot in develop:

```
Dec  6 16:30:16 sfci-1pfefh sh[2969]: Traceback (most recent call last):
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     sys.exit(main())
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 169, in main
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     _audit_daemons()
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 162, in _audit_daemons
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     _start_daemon(d)
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 103, in _start_daemon
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 188, in run
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     self._process_network_node_workitems()
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 154, in _process_network_node_workitems
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     n.create()
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 320, in create
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     self.deploy_nat()
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 358, in deploy_nat
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     'dev %(physical_veth_inner)s' % subst)
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 285, in execute
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     env_variables=env_variables, shell=True)
Dec  6 16:30:16 sfci-1pfefh sh[2969]:   File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 441, in execute
Dec  6 16:30:16 sfci-1pfefh sh[2969]:     cmd=sanitized_cmd)
Dec  6 16:30:16 sfci-1pfefh sh[2969]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Dec  6 16:30:16 sfci-1pfefh sh[2969]: Command: ip netns exec 3467bc57-8059-4fd7-9e93-3db2ed9baad4 ip addr add 192.168.20.234/255.255.255.0 dev phy-4-i
Dec  6 16:30:16 sfci-1pfefh sh[2969]: Exit code: 1
Dec  6 16:30:16 sfci-1pfefh sh[2969]: Stdout: ''
Dec  6 16:30:16 sfci-1pfefh sh[2969]: Stderr: 'Cannot find device "phy-4-i"\n'
```

The weird bit is that this shouldn't have been queued as a task. For single node CI the hypervisor node is also the network node and this should have been fast pathed to avoid the queue. I need to debug this further.

**Comment by mandoonandy** [comment]
As a side comment: I think there should a single path for actions such as this - even if a small efficiency was available.

If the creation of a 'thing' uses a queue, then it should always go through the same 'thing queue'. The usual benefits of reduced code, maintainability, etc...

**Comment by mikalstill** [comment]
I think this is now resolved with randomized vxlan ids.
