### ISSUE TITLE
Key error in power states

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#584]
```
Dec  7 23:41:17 sfci-smk6su INFO sf-cleaner[16899] Updating power states
Dec  7 23:41:17 sfci-smk6su sh[2913]: Traceback (most recent call last):
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Dec  7 23:41:17 sfci-smk6su sh[2913]:     sys.exit(main())
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 182, in main
Dec  7 23:41:17 sfci-smk6su sh[2913]:     _audit_daemons()
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 162, in _audit_daemons
Dec  7 23:41:17 sfci-smk6su sh[2913]:     _start_daemon(d)
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 103, in _start_daemon
Dec  7 23:41:17 sfci-smk6su sh[2913]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/cleaner.py", line 160, in run
Dec  7 23:41:17 sfci-smk6su sh[2913]:     self._update_power_states()
Dec  7 23:41:17 sfci-smk6su sh[2913]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/cleaner.py", line 125, in _update_power_states
Dec  7 23:41:17 sfci-smk6su sh[2913]:     elif dbpowerstate['power_state'] != 'off':
Dec  7 23:41:17 sfci-smk6su sh[2913]: KeyError: 'power_state'
```

**Comment by mikalstill** [comment]
This might be a missing initial value like state was? I need to work out what happened before the refactor.
