### ISSUE TITLE
Nightly develop CI failing with exception

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#590]
```
Dec 12 23:21:40 jenkins-201212-zae1je4y-sf-1 ERROR gunicorn: worker [sf-api][12841] Server error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 732, in post
    candidates = SCHEDULER.place_instance(instance, network)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/scheduler.py", line 242, in place_instance
    requested_networks, candidates)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/scheduler.py", line 84, in _find_most_matching_networks
    per_node.setdefault(inst['node'], [])
KeyError: 'node'
```

**Comment by mikalstill** [comment]
Released.
