### ISSUE TITLE
Download errors for cirros are messy for API clients

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#592]
On the server:

```
Dec 14 20:22:58 sfci-hduchz ERROR gunicorn: worker [sf-api][5238] Server error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb2f2274a20>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='download.cirros-cloud.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2f2274a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 732, in post
    candidates = SCHEDULER.place_instance(instance, network)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/scheduler.py", line 254, in place_instance
    img = images.Image.from_url(disk['base'])
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 81, in from_url
    url, resolver_checksum = Image._resolve(url)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 60, in _resolve
    return resolvers[resolver].resolve(url)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/image_resolver_cirros.py", line 17, in resolve
    headers={'User-Agent': util.get_user_agent()})
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='download.cirros-cloud.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2f2274a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Dec 14 20:22:58 sfci-hduchz INFO gunicorn: worker [sf-api][5238] Returning API error: 500, server error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='download.cirros-cloud.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2f2274a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
```

On the client:

```
shakenfist_client.apiclient.InternalServerError: ('API request failed', 'POST', 'http://sf-1:13000/instances', 500, '{"error": "server error: ConnectionError(MaxRetryError(\\"HTTPConnectionPool(host=\'download.cirros-cloud.net\', port=80): Max retries exceeded with url: / (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7fb2f2274a20>: Failed to establish a new connection: [Errno -2] Name or service not known\',))\\",),)", "status": 500}')
```

We can wrap this more nicely I think.

**Comment by mikalstill** [comment]
Fixed. Image fetching is now an async operation that catches connection/DNS failures, normalises the message, and sets the artifact to error state rather than returning a raw 500 traceback (`shakenfist/operations/artifact_fetch_op.py:122`).

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
