### ISSUE TITLE
Net daemon crashes after upgrade

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#609]
Upgrade needs to rename interface to new 6 char hex name extension.
```
Dec 29 12:15:57 sf-3 INFO sf-net[9845] Finish create vxlan interface; duration=0.02299785614013672; network=d56db115-8321-4c0a-b70f-821d6b28c22d
Dec 29 12:15:57 sf-3 sh[9194]: Traceback (most recent call last):
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Dec 29 12:15:57 sf-3 sh[9194]:     sys.exit(main())
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 182, in main
Dec 29 12:15:57 sf-3 sh[9194]:     _audit_daemons()
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 162, in _audit_daemons
Dec 29 12:15:57 sf-3 sh[9194]:     _start_daemon(d)
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/main.py", line 103, in _start_daemon
Dec 29 12:15:57 sf-3 sh[9194]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 198, in run
Dec 29 12:15:57 sf-3 sh[9194]:     self._maintain_networks()
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/net.py", line 95, in _maintain_networks
Dec 29 12:15:57 sf-3 sh[9194]:     n.create_on_hypervisor()
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 309, in create_on_hypervisor
Dec 29 12:15:57 sf-3 sh[9194]:     self._create_common()
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/net.py", line 283, in _create_common
Dec 29 12:15:57 sf-3 sh[9194]:     % subst)
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 144, in create_interface
Dec 29 12:15:57 sf-3 sh[9194]:     'extra': extra})
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/shakenfist/util.py", line 287, in execute
Dec 29 12:15:57 sf-3 sh[9194]:     env_variables=env_variables, shell=True)
Dec 29 12:15:57 sf-3 sh[9194]:   File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 434, in execute
Dec 29 12:15:57 sf-3 sh[9194]:     cmd=sanitized_cmd)
Dec 29 12:15:57 sf-3 sh[9194]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Dec 29 12:15:57 sf-3 sh[9194]: Command: ip link add vxlan-000004 type vxlan id 4 dev ens160 dstport 0
Dec 29 12:15:57 sf-3 sh[9194]: Exit code: 2
Dec 29 12:15:57 sf-3 sh[9194]: Stdout: ''
Dec 29 12:15:57 sf-3 sh[9194]: Stderr: 'Error: A VXLAN device with the specified VNI already exists.\n'

Dec 29 12:16:02 sf-1 WARNING sf-main[2950] net died (pid 3726)
```

**Comment by mikalstill** [comment]
Are you working on the longer term fix for this one, or should I?

**Comment by mandoonandy** [comment]
I haven't started. Hopefully it's just an upgrade step. I probably will not get to it for a couple of days.

**Comment by mikalstill** [comment]
So, I'm thinking there are two options... We somehow rename interfaces during upgrade (simple, if possible). Or we fall back to old style names when they're detected at runtime. Thoughts?

**Comment by mikalstill** [comment]
Turns out you can rename an interface, but it needs to be down when you do it. Something like:

```
ip link set vxlan-1 down
ip link set vxlan-1 name vxlan-000001
ip link set vxlan-000001 up
```
