### ISSUE TITLE
Missed Image.from_url conversion in daemons/main.py

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#618]
```
Jan  2 09:10:52 cbr-sf-2 sh[1814683]: Traceback (most recent call last):
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:     sys.exit(main())
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 189, in main
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:     restore_instances()
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 41, in restore_instances
Jan  2 09:10:52 cbr-sf-2 sh[1814683]:     img = images.Image.from_url(disk['base'])
Jan  2 09:10:52 cbr-sf-2 sh[1814683]: AttributeError: type object 'Image' has no attribute 'from_url'
```

**Comment by mandoonandy** [comment]
Dupe #616

**Comment by mandoonandy** [comment]
Snap
