### ISSUE TITLE
Image Object: Missing parameter from DB causes exception

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#623]
Upgraded system with all images deleted. Started new instance requiring image download.
```
Jan  2 20:24:10 sf-3 INFO sf-queues-1609579445.7002475-000[22037] Unable to retrieve MD5SUMS for cirros image; url=http://download.cirros-cloud.net/0.5.1/cirros-0.5.1-x86_64-disk.img
Jan  2 20:24:10 sf-3 ERROR sf-queues-1609579445.7002475-000[22037] [Exception] Ignored error in sf-queues: 'sequence'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/queues.py", line 71, in handle
    image_fetch(task.url(), instance_uuid)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/daemons/queues.py", line 134, in image_fetch
    img.get([lock], instance)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 215, in get
    return self._get(locks, related_object)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 237, in _get
    actual_image = self.version_image_path()
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/images.py", line 233, in version_image_path
    self.latest_download_version['sequence'] + inc)
KeyError: 'sequence'
```

**Comment by mikalstill** [comment]
Released.
