### ISSUE TITLE
Client cannot handle broken instances

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#635]
When an instance has not been placed on a node
```
$ sf-client instance list
Traceback (most recent call last):
  File "/home/andy/.local/bin/sf-client", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/main.py", line 27, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click-7.1.2-py3.8.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/main.py", line 631, in instance_list
    i['cpus'], i['memory'], i['node'],
KeyError: 'node'
```
Correct output should be:
```
$ sf-client instance list
+--------------------------------------+------+-----------+------+--------+------------+-------------+---------+
|                 uuid                 | name | namespace | cpus | memory | hypervisor | power state |  state  |
+--------------------------------------+------+-----------+------+--------+------------+-------------+---------+
| 1dacbbfc-27eb-4e3a-87a1-0631803fb36b | bob  |   system  |  1   |  1024  |    sf-3    |      on     | created |
| a04f89c5-15db-4163-a3b8-f6cc5538e467 | bob  |   system  |  1   |  1024  |    sf-2    |      on     | created |
| b59be5e9-239b-4202-be20-203a9f85c935 | bob  |   system  |  1   |  1024  |    sf-2    |      on     | created |
| d51e0cc0-6988-4760-9ef4-6602487a03b4 | bob  |   system  |  1   |  1024  |    None    |   initial   | initial |
+--------------------------------------+------+-----------+------+--------+------------+-------------+---------+

**Comment by mikalstill** [comment]
Released.
