### ISSUE TITLE
We don't handle failed boots very well

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#643]
```
sf-client instance create 001-resized 2 2048 -n db925ee6-5994-4858-99df-92d37bc7db26 -d 30@https://overlord.hex3544.org/632684ed-69ab-4ea9-a51b-8acdb947da57/extracted_images/84212731-3a5a-4ac1-b970-1a280f77ebd5/20201130/001-ext-resized.qcow2
Traceback (most recent call last):
  File "/usr/local/bin/sf-client", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/main.py", line 27, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/main.py", line 927, in instance_create
    _show_instance(
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/main.py", line 677, in _show_instance
    interfaces = CLIENT.get_instance_interfaces(i['uuid'])
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/apiclient.py", line 192, in get_instance_interfaces
    r = self._request_url('GET', self.base_url + '/instances/' + instance_uuid +
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/apiclient.py", line 172, in _request_url
    raise e
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/apiclient.py", line 162, in _request_url
    return self._actual_request_url(method, url, data=data)
  File "/usr/local/lib/python3.8/dist-packages/shakenfist_client/apiclient.py", line 133, in _actual_request_url
    raise STATUS_CODES_TO_ERRORS[r.status_code](
shakenfist_client.apiclient.DependenciesNotReadyException: ('API request failed', 'GET', 'http://localhost:13000/instances/c5ab0e4e-58fc-435e-90ff-37e1a7423acd/interfaces', 406, '{"error": "instance not active", "status": 406}')
```

**Comment by mikalstill** [comment]
On reflection, I don't think this is a failed boot. This is an image taking a long time to download and then the API refusing to provide information about incomplete objects.
