### ISSUE TITLE
CI broken by dependancy upgrade

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#699]
The CI pipeline for master is returning lots of errors like this:

```
shakenfist.tests.test_external_api.ExternalApiInstanceTestCase.test_post_instance_invalid_network
-------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/home/mikal/src/shakenfist/shakenfist/shakenfist/tests/test_external_api.py", line 871, in test_post_instance_invalid_network
    self.assertEqual(

      File "/home/mikal/src/shakenfist/shakenfist/.tox/py3/lib/python3.8/site-packages/testtools/testcase.py", line 415, in assertEqual
    self.assertThat(observed, matcher, message)

      File "/home/mikal/src/shakenfist/shakenfist/.tox/py3/lib/python3.8/site-packages/testtools/testcase.py", line 502, in assertThat
    raise mismatch_error

    testtools.matchers._impl.MismatchError: !=:
reference = {'error': 'network specification should contain JSON objects', 'status': 400}
actual    = {'error': "wrapper() got an unexpected keyword argument 'name'",
 'status': 400,
 'traceback': 'Traceback (most recent call last):\n'
              '  File '
              '"/home/mikal/src/shakenfist/shakenfist/shakenfist/external_api/app.py", '
              'line 138, in wrapper\n'
              '    return func(*args, **kwargs)\n'
              'TypeError: wrapper() got an unexpected keyword argument '
              "'name'\n"}
```

I didn't see these on my laptop until I cleared my tox environment (which means I now get the latest versions of packages), at which point it fails for me too. This feels like a dependancy has broken us?

**Comment by mikalstill** [comment]
I wrote a quick script to see what had released recently:

```
$ python3 pipnew.py | grep 2021-02
Latest release of ansible is 3.0.0rc1 from 2021-02-09 23:05:24.486813+00:00
Latest release of ansible-base is 2.10.6rc1 from 2021-02-09 02:22:54.305884+00:00
Latest release of cryptography is 3.4.5 from 2021-02-13 22:51:26.246678+00:00
Latest release of Flask-JWT-Extended is 4.0.2 from 2021-02-13 21:06:23.219838+00:00
Latest release of itsdangerous is 2.0.0rc1 from 2021-02-15 16:53:16.666304+00:00
Latest release of MarkupSafe is 2.0.0rc1 from 2021-02-15 16:34:00.615188+00:00
Latest release of more-itertools is 8.7.0 from 2021-02-08 01:53:03.653795+00:00
Latest release of pytz is 2021.1 from 2021-02-01 08:07:15.659674+00:00
Latest release of SecretStorage is 3.3.1 from 2021-02-09 12:02:57.556353+00:00
Latest release of shakenfist is 0.4.2 from 2021-02-06 06:02:08.298612+00:00
Latest release of tox is 4.0.0a6 from 2021-02-15 08:11:01.629394+00:00
Latest release of virtualenv is 20.4.2 from 2021-02-01 09:17:59.258791+00:00
Latest release of Werkzeug is 2.0.0rc1 from 2021-02-08 15:20:44.821674+00:00
```

**Comment by mikalstill** [comment]
```
$ diff -u packages-working.txt packages-broken.txt 
--- packages-working.txt	2021-02-16 15:00:31.653010298 +1100
+++ packages-broken.txt	2021-02-16 16:37:26.270711047 +1100
@@ -33,7 +33,7 @@
 fixtures               3.0.0
 flake8                 3.8.4
 Flask                  1.1.2
-Flask-JWT-Extended     3.25.0
+Flask-JWT-Extended     4.0.2
 Flask-RESTful          0.3.8
 futurist               2.3.0
 grpcio                 1.35.0
@@ -89,7 +89,7 @@
 pyflakes               2.2.0
 PyGObject              3.36.0
 PyHamcrest             1.9.0
-PyJWT                  1.7.1
+PyJWT                  2.0.1
 pykerberos             1.1.14
 pylogrus               0.4.0
 pyOpenSSL              19.0.0
@@ -112,8 +112,8 @@
 service-identity       18.1.0
 setproctitle           1.2.2
 setuptools             53.0.0
-shakenfist             0.0.1.dev1283
-shakenfist-client      0.4.3.dev9
+shakenfist             0.3.4
+shakenfist-client      0.3.4
 simplejson             3.16.0
 six                    1.14.0
 sos                    4.0
```
