### ISSUE TITLE
Issue starting an instance

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#728]
Not sure what is happening here:

```
Mar 27 13:49:22 sf-3 INFO sf-queues-1616813218.8238313-000[31888] Enqueued workitem; jobname=1616813362.6035175-000; queuename=networknode; workitem=QueueTask:UpdateD
HCPNetworkTask: {'task': 'network_update_dhcp', 'version': 1, 'network_uuid': '2202ee95-0eb9-464a-9379-2c23ccb23664'}
Mar 27 13:49:22 sf-3 INFO sf-queues-1616813218.8238313-000[31888] Added event; duration=None; fqdn=sf-3; message=None; network=2202ee95-0eb9-464a-9379-2c23ccb23664; o
peration=update dhcp; phase=enqueued
Mar 27 13:49:22 sf-3 INFO sf-queues-1616813218.8238313-000[31888] Added event; duration=None; fqdn=sf-3; instance=6a34ef17-aa44-4950-be42-6343a8f2d391; message=None; 
operation=instance creation; phase=start
Mar 27 13:49:22 sf-3 INFO sf-queues-1616813218.8238313-000[31888] Added event; duration=0.021524906158447266; fqdn=sf-3; instance=6a34ef17-aa44-4950-be42-6343a8f2d391
; message=None; operation=instance creation; phase=finish
Mar 27 13:49:22 sf-3 INFO sf-queues-1616813218.8238313-000[31888] Finish instance creation; duration=0.021524906158447266; instance=6a34ef17-aa44-4950-be42-6343a8f2d3
91
Mar 27 13:49:22 sf-3 ERROR sf-queues-1616813218.8238313-000[31888] [Exception] Ignored error in sf-queues: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 87, in handle
    instance_start(instance, task.network())
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 225, in instance_start
    instance.create(lock=lock)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/virt.py", line 372, in create
    self.state = self.STATE_CREATING
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/baseobject.py", line 104, in state
    if new_value not in self.state_targets.get(orig.value, []):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by mikalstill** [comment]
Start command was:

```
sf-client instance create --namespace mikal ubuntu-desktop 2 2048 -d 20 -d 3@http://sf-primary/static/ubuntu-20.04.2.0-desktop-amd64.iso -n 2202ee95-0eb9-464a-9379-2c23ccb23664 -i id_general.pub
```

**Comment by mikalstill** [comment]
Actually, its probably this:

```
Mar 27 14:15:39 sf-3 ERROR sf-queues-1616814938.0217845-000[500] [Exception] Ignored error in sf-queues: Unexpected error while running command.
Command: qemu-img convert -t none -O qcow2 /srv/shakenfist/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002 /srv/shakenfist/image_cac
he/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002.qcow2
Exit code: 1
Stdout: ''
Stderr: "qemu-img: Could not open '/srv/shakenfist/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002': Could not open '/srv/shakenfist
/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002': No such file or directory\n"
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 76, in handle
    image_fetch(task.url(), instance)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 135, in image_fetch
    img.get([lock], instance)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/images.py", line 229, in get
    image_path = self._get(locks, related_object)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/images.py", line 281, in _get
    _transcode(locks, actual_image, related_object)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/images.py", line 420, in _transcode
    create_qcow2(locks, actual_image, actual_image + '.qcow2')
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/images.py", line 526, in create_qcow2
    % (cache_file, disk_file))
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/util.py", line 306, in execute
    env_variables=env_variables, shell=True)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/oslo_concurrency/processutils.py", line 441, in execute
    cmd=sanitized_cmd)
oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Command: qemu-img convert -t none -O qcow2 /srv/shakenfist/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002 /srv/shakenfist/image_cac
he/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002.qcow2
Exit code: 1
Stdout: ''
Stderr: "qemu-img: Could not open '/srv/shakenfist/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002': Could not open '/srv/shakenfist
/image_cache/139460e48e9d7dd560d5b1788a2abead091c6e50836fdb1f7897a984da644f87.v002': No such file or directory\n"
```

**Comment by mikalstill** [comment]
I think this might be a race where locking isn't working quite right because of the distributed image store that gluster creates?
