### ISSUE TITLE
Creating an instance fails but returns 200 

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/shakenfist#74]
Creating an instance randomly returns an empty data structure with a 200 OK.
The instance is subsequently created.

```
**************************
*** Create an instance ***
**************************
UUID: 
Name: 
CPUs: 0
Memory (MB): 0
Disks:
SSHKey: 
Node: 
ConsolePort: 0
VDIPort: 0
UserData: 
State: 
StateUpdated: 1970-01-01 10:00:00 +1000 AEST
```

**Comment by mikalstill** [comment]
Interesting. I cannot see a place where a return wouldn't have had an instance in it... Do you have logs from the server you sent the request to, and any server it needed to proxy to post scheduling?

**Comment by mandoonandy** [comment]
I'm re-running on the latest master merge, then I'll attach some logs.
(Got a bug whilst doing that)

**Comment by mandoonandy** [comment]
As suspected, the create instance goes to sf-1 but is proxied to sf-3. It's an auth problem between the servers.
```Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 External API request: <Request 'http://localhost:13000/instances' [POST]>
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 External API request: <bound method Instances.post of <shakenfist.external_api.app.Instances object at 0x7fb0e1440710>> () {'name': 'golang', 'cpus': 1, 'memory': 1, 'network': [{'network_uuid': '2ed1730d-c64a-4e58-8e63-a3353838b1a9', 'address': '', 'macaddress': '', 'model': ''}], 'disk': [{'base': 'cirros', 'size': 8, 'bus': '', 'type': 'disk'}], 'ssh_key': '', 'user_data': ''}
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 instance(efc9ebbc-a729-425b-b004-f3b80c42370c): Start schedule
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] start as candidates
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have enough actual CPU
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have enough idle CPU
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have enough idle RAM
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have enough idle disk
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 kernel: [13328.354275] IPv6: ADDRCONF(NETDEV_CHANGE): br-vxlan-9: link becomes ready
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 systemd-networkd[4850]: br-vxlan-9: Gained carrier
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have most matching networks
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 Scheduling instance(efc9ebbc-a729-425b-b004-f3b80c42370c), ['sf-1', 'sf-2', 'sf-3'] have most matching images
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-1 instance(efc9ebbc-a729-425b-b004-f3b80c42370c): Finish schedule, duration 0.11 seconds
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-3 External API request: <Request 'http://sf-3:13000/instances' [POST]>
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-3 External API request: <bound method Instances.post of <shakenfist.external_api.app.Instances object at 0x7f99a45866a0>> () {'name': 'golang', 'cpus': 1, 'memory': 1, 'network': [{'network_uuid': '2ed1730d-c64a-4e58-8e63-a3353838b1a9', 'address': '', 'macaddress': '', 'model': ''}], 'disk': [{'base': 'cirros', 'size': 8, 'bus': '', 'type': 'disk'}], 'ssh_key': '', 'user_data': '', 'placed_on': 'sf-3', 'instance_uuid': 'efc9ebbc-a729-425b-b004-f3b80c42370c'}
Jun 23 08:22:59 andy-200623-fiu9eiqu-sf-3 Returning API error: 500, server error#012    Traceback (most recent call last):#012      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 91, in wrapper#012        return func(*args, **kwargs)#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper#012        verify_jwt_in_request()#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request#012        jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 314, in _decode_jwt_from_request#012        raise NoAuthorizationError(errors[0])#012    flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
```

**Comment by mikalstill** [comment]
Good catch.
