### ISSUE TITLE
Floating IPs broken

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#783]
```
May  3 15:37:27 sf-1 INFO sf-net[8019] Executing ip netns exec 5cf6701e-7085-4d9d-af39-7e316cd57f37 iptables -t nat -A PREROUTING -d 192.168.10.101 -j DNAT --to-destination None with locks None
May  3 15:37:27 sf-1 INFO sf-net[8019] Resolved workitem; jobname=1620020246.9431953-000; queuename=networknode
May  3 15:37:27 sf-1 sh[7961]: Traceback (most recent call last):
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/bin/sf-daemon", line 10, in <module>
May  3 15:37:27 sf-1 sh[7961]:     sys.exit(main())
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/main.py", line 225, in main
May  3 15:37:27 sf-1 sh[7961]:     _audit_daemons()
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/main.py", line 218, in _audit_daemons
May  3 15:37:27 sf-1 sh[7961]:     _start_daemon(d)
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/main.py", line 119, in _start_daemon
May  3 15:37:27 sf-1 sh[7961]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/net.py", line 254, in run
May  3 15:37:27 sf-1 sh[7961]:     self._process_network_node_workitems()
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/net.py", line 239, in _process_network_node_workitems
May  3 15:37:27 sf-1 sh[7961]:     self._process_networkinterface_workitem(log_ctx, workitem)
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/net.py", line 216, in _process_networkinterface_workitem
May  3 15:37:27 sf-1 sh[7961]:     n.add_floating_ip(ni['floating'], ni['ipv4'])
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/net.py", line 668, in add_floating_ip
May  3 15:37:27 sf-1 sh[7961]:     % subst)
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/util.py", line 296, in execute
May  3 15:37:27 sf-1 sh[7961]:     env_variables=env_variables, shell=True)
May  3 15:37:27 sf-1 sh[7961]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/oslo_concurrency/processutils.py", line 441, in execute
May  3 15:37:27 sf-1 sh[7961]:     cmd=sanitized_cmd)
May  3 15:37:27 sf-1 sh[7961]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
May  3 15:37:27 sf-1 sh[7961]: Command: ip netns exec 5cf6701e-7085-4d9d-af39-7e316cd57f37 iptables -t nat -A PREROUTING -d 192.168.10.101 -j DNAT --to-destination None
May  3 15:37:27 sf-1 sh[7961]: Exit code: 2
May  3 15:37:27 sf-1 sh[7961]: Stdout: ''
May  3 15:37:27 sf-1 sh[7961]: Stderr: 'iptables v1.8.2 (nf_tables): Bad IP address "None"\n\nTry `iptables -h\' or \'iptables --help\' for more information.\n'
May  3 15:37:35 sf-1 WARNING sf-main[7962] net died (pid 8019)
```

**Comment by mikalstill** [comment]
The inner IP is None for some reason.

**Comment by mikalstill** [comment]
This is actually a client issue as best as I can tell.
