### ISSUE TITLE
Instance delete is failing

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#81]
```
$ for uuid in `sf-client --simple instance list | grep -v uuid | cut -f 1 -d "," | head -1`; do   sf-client instance delete $uuid; done
Traceback (most recent call last):
  File "/usr/local/bin/sf-client", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/main.py", line 533, in instance_delete
    CLIENT.delete_instance(instance_uuid)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/apiclient.py", line 186, in delete_instance
    '/instances/' + instance_uuid)
  File "/usr/local/lib/python3.6/dist-packages/shakenfist/client/apiclient.py", line 109, in _request_url
    'API request failed', method, url, r.status_code, r.text)
shakenfist.client.apiclient.APIException: ('API request failed', 'DELETE', 'http://localhost:13000/instances/23000e33-25cd-47f2-a857-6ca6721cc86f', 500, '{"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\\", line 91, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\\", line 107, in wrapper\\n    verify_jwt_in_request()\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\\", line 32, in verify_jwt_in_request\\n    jwt_data, jwt_header = _decode_jwt_from_request(request_type=\'access\')\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\\", line 294, in _decode_jwt_from_request\\n    decoded_token = decode_token(encoded_token, csrf_token)\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/utils.py\\", line 118, in decode_token\\n    allow_expired=allow_expired\\n  File \\"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/tokens.py\\", line 140, in decode_jwt\\n    leeway=leeway, options=options, issuer=issuer)\\n  File \\"/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py\\", line 92, in decode\\n    jwt, key=key, algorithms=algorithms, options=options, **kwargs\\n  File \\"/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py\\", line 156, in decode\\n    key, algorithms)\\n  File \\"/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py\\", line 223, in _verify_signature\\n    raise InvalidSignatureError(\'Signature verification failed\')\\njwt.exceptions.InvalidSignatureError: Signature verification failed\\n"}')
```

**Comment by mikalstill** [comment]
Another example of proxy auth issues:

```
Jun 23 20:29:36 sf-2 External API request: <Request 'http://sf-2:13000/instances/23000e33-25cd-47f2-a857-6ca6721cc86f' [DELETE]>
Jun 23 20:29:36 sf-2 External API request: <bound method arg_is_instance_uuid_as_virt.<locals>.wrapper of <shakenfist.external_api.app.Instance object at 0x7f7ddc0c0518>> () {'instance_uuid': '23000e33-25cd-47f2
-a857-6ca6721cc86f'}
Jun 23 20:29:36 sf-2 Returning API error: 500, server error#012    Traceback (most recent call last):#012      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 91, in wrapper#01
2        return func(*args, **kwargs)#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper#012        verify_jwt_in_request()#012      File "/usr/loc
al/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request#012        jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')#012      File "/usr/loca
l/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request#012        decoded_token = decode_token(encoded_token, csrf_token)#012      File "/usr/local/lib/python
3.6/dist-packages/flask_jwt_extended/utils.py", line 118, in decode_token#012        allow_expired=allow_expired#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/tokens.py", line 140, in 
decode_jwt#012        leeway=leeway, options=options, issuer=issuer)#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py", line 92, in decode#012        jwt, key=key, algorithms=algorithms, opti
ons=options, **kwargs#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py", line 156, in decode#012        key, algorithms)#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py",
 line 223, in _verify_signature#012        raise InvalidSignatureError('Signature verification failed')#012    jwt.exceptions.InvalidSignatureError: Signature verification failed
Jun 23 20:29:36 sf-1 Proxied DELETE http://sf-2:13000/instances/23000e33-25cd-47f2-a857-6ca6721cc86f returns: 500, {"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\n  Fil
e \"/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py\", line 91, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 107, in wrapper\n    verify_jwt_in_request()\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 32, in verify_jwt_in_request\n    jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py\", line 294, in _decode_jwt_from_request\n    decoded_token = decode_token(encoded_token, csrf_token)\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/utils.py\", line 118, in decode_token\n    allow_expired=allow_expired\n  File \"/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/tokens.py\", line 140, in decode_jwt\n    leeway=leeway, options=options, issuer=issuer)\n  File \"/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py\", line 92, in decode\n    jwt, key=key, algorithms=algorithms, options=options, **kwargs\n  File \"/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py\", line 156, in decode\n    key, algorithms)\n  File \"/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py\", line 223, in _verify_signature\n    raise InvalidSignatureError('Signature verification failed')\njwt.exceptions.InvalidSignatureError: Signature verification failed\n"}
Jun 23 20:29:36 localhost gunicorn.sf.access: [29108] 127.0.0.1 - - [23/Jun/2020:20:29:36 +1000] "DELETE /instances/23000e33-25cd-47f2-a857-6ca6721cc86f HTTP/1.1" 500 1551 "-" "Mozilla/5.0 (Ubuntu; Linux x86_64) ShakenFist/0.1.2"
```

**Comment by mikalstill** [comment]
It seems like we can't just pass the Authorization header around like we do?

```
Jun 23 20:29:36 sf-2 External API request: <Request 'http://sf-2:13000/instances/23000e33-25cd-47f2-a857-6ca6721cc86f' [DELETE]>
Jun 23 20:29:36 sf-2 External API request: <bound method arg_is_instance_uuid_as_virt.<locals>.wrapper of <shakenfist.external_api.app.Instance object at 0x7f7ddc0c0518>> () {'instance_uuid': '23000e33-25cd-47f2
-a857-6ca6721cc86f'}
Jun 23 20:29:36 sf-2 Returning API error: 500, server error#012    Traceback (most recent call last):#012      File "/usr/local/lib/python3.6/dist-packages/shakenfist/external_api/app.py", line 91, in wrapper#01
2        return func(*args, **kwargs)#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 107, in wrapper#012        verify_jwt_in_request()#012      File "/usr/loc
al/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 32, in verify_jwt_in_request#012        jwt_data, jwt_header = _decode_jwt_from_request(request_type='access')#012      File "/usr/loca
l/lib/python3.6/dist-packages/flask_jwt_extended/view_decorators.py", line 294, in _decode_jwt_from_request#012        decoded_token = decode_token(encoded_token, csrf_token)#012      File "/usr/local/lib/python
3.6/dist-packages/flask_jwt_extended/utils.py", line 118, in decode_token#012        allow_expired=allow_expired#012      File "/usr/local/lib/python3.6/dist-packages/flask_jwt_extended/tokens.py", line 140, in 
decode_jwt#012        leeway=leeway, options=options, issuer=issuer)#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jwt.py", line 92, in decode#012        jwt, key=key, algorithms=algorithms, opti
ons=options, **kwargs#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py", line 156, in decode#012        key, algorithms)#012      File "/usr/local/lib/python3.6/dist-packages/jwt/api_jws.py",
 line 223, in _verify_signature#012        raise InvalidSignatureError('Signature verification failed')#012    jwt.exceptions.InvalidSignatureError: Signature verification failed
```

**Comment by mikalstill** [comment]
But then it worked before. I wonder if this is a token expiry thing?

**Comment by mikalstill** [comment]
The docs say the default is a 15 minute lifetime for a token, so that seems unlikely? https://flask-jwt-extended.readthedocs.io/en/stable/options/#configuration-options

**Comment by mikalstill** [comment]
This is definitely repeatedly happening to me. Further debugging required.

**Comment by mikalstill** [comment]
New theory, I need to generate a new token for that user before proxying the request, like I do for admin tokens.
