### ISSUE TITLE
Modern cloud-init has issues with network interfaces with no address

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#856]
I see this with cloud-init version XXX:

```
[    5.967055] cloud-init[697]: 2021-08-10 01:07:25,572 - network_state.py[ERROR]: No config network address keys [address] found in {u'type': 'static', 'ipv4': True}
[    5.976401] cloud-init[697]: 2021-08-10 01:07:25,573 - util.py[WARNING]: failed stage init-local
[    5.983462] cloud-init[697]: failed run of stage init-local
[    5.985849] cloud-init[697]: ------------------------------------------------------------
[    5.988818] cloud-init[697]: Traceback (most recent call last):
[    5.991284] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
[    5.994632] cloud-init[697]: ret = functor(name, args)
[    5.996939] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/cmd/main.py", line 362, in main_init
[    6.000293] cloud-init[697]: init.apply_network_config(bring_up=bool(mode != sources.DSMODE_LOCAL))
[    6.003366] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 711, in apply_network_config
[    6.007543] cloud-init[697]: return self.distro.apply_network_config(netcfg, bring_up=bring_up)
[    6.014445] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/distros/__init__.py", line 178, in apply_network_config
[    6.016604] cloud-init[697]: dev_names = self._write_network_config(netconfig)
[    6.016859] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/distros/rhel.py", line 65, in _write_network_config
[    6.017173] cloud-init[697]: return self._supported_write_network_config(netconfig)
[    6.017453] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/distros/__init__.py", line 93, in _supported_write_network_config
[    6.017762] cloud-init[697]: renderer.render_network_config(network_config)
[    6.018057] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/renderer.py", line 55, in render_network_config
[    6.018350] cloud-init[697]: network_state=parse_net_config_data(network_config),
[    6.018639] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 78, in parse_net_config_data
[    6.019520] cloud-init[697]: nsi.parse_config(skip_broken=skip_broken)
[    6.019820] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 292, in parse_config
[    6.020134] cloud-init[697]: self.parse_config_v1(skip_broken=skip_broken)
[    6.020420] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 307, in parse_config_v1
[    6.020732] cloud-init[697]: handler(self, command)
[    6.021034] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 125, in decorator
[    6.021325] cloud-init[697]: return func(self, command, *args, **kwargs)
[    6.021613] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 360, in handle_physical
[    6.021907] cloud-init[697]: subnets = _normalize_subnets(command.get('subnets'))
[    6.022528] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 930, in _normalize_subnets
[    6.022819] cloud-init[697]: return [_normalize_subnet(s) for s in subnets]
[    6.023118] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 825, in _normalize_subnet
[    6.023405] cloud-init[697]: _normalize_net_keys(normal_subnet, address_keys=('address',)))
[    6.023694] cloud-init[697]: File "/usr/lib/python2.7/site-packages/cloudinit/net/network_state.py", line 861, in _normalize_net_keys
[    6.023985] cloud-init[697]: raise ValueError(message)
[    6.024572] cloud-init[697]: ValueError: No config network address keys [address] found in {u'type': 'static', 'ipv4': True}
[    6.024864] cloud-init[697]: ------------------------------------------------------------
[ESC[1;31mFAILEDESC[0m] Failed to start Initial cloud-init job (pre-networking).
```

**Comment by mikalstill** [comment]
This was fixed, but the commit didn't use the right keyword to autoclose this bug.
