### ISSUE TITLE
KeyError when you use a label which doesn't exist

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#864]
```
fatal: [localhost]: FAILED! => {"changed": false, "meta": "Command failed: ERROR: Internal Server Error: {\"error\": \"server error: KeyError('blob_uuid')\", \"status\": 500}\n", "msg": "Error manipulating instance", "params": {"cpu": "4", "disks": ["30@label:sfci-image"], "diskspecs": null, "name": "mikal", "networks": null, "networkspecs": ["network_uuid=\"16716b80-1217-4899-87c0-2ce2b6494136\",float=True"], "placement": null, "ram": "4096", "ssh_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+482i1EYa6FYmDrjOQpsm+mVwFs7TW9xOI9o1jc/PHXLDDg5+inp/vVAgKoV6jijwRC9juwjFBPqr8LyXh3lXhPA1LSaQa39o3QIYTLsLuLZPeueUB8UukZzOH0XAHxgAF/qFycf5pWzD4Pzs5HjNi44+9LCDYKJtc45kh3+97iezRMYhucm3wzRAKyA8mr8nNOrQq356sKgXeMP6nnX4bhUJDrcQpfsRFkTcYWAcSuU36eSETVOj9dGUJZlc4g3QBL73R1S5VWbN6DM4UIOSWxRG6oUKprgHSvFmyp5i7S0vKv7q101PcxOw14GOvI8TSirIa8O39WtyX3ugReBj mikal@sf-primary", "state": "present", "uefi": null, "user_data": null, "uuid": null, "video": null}}
```

**Comment by mikalstill** [comment]
It looks like labels aren't updating the blob_uuid correctly?

```
Aug 14 10:51:55 sf-1 INFO gunicorn: worker [sf-api][13687] API request: POST http://192.168.1.51:13000/instances
    Args: ()
    KWargs: {'name': 'jenkins-shakenfist-develop-rebuild-ci-image-30', 'cpus': 4, 'memory': 4096, 'network': [{'network_uuid': '37da8dd8-29d0-4e25-b73c-e949f06a087e', 'float': True}], 'ssh_key': '...', 'user_data': None, 'namespace': None, 'video': {'model': 'cirrus', 'memory': 16384}, 'uefi': False, 'disk': [{'size': 30, 'base': 'label:sfci-image', 'bus': None, 'type': 'disk'}]}
Aug 14 10:51:55 sf-1 ERROR gunicorn: worker [sf-api][13687] Server error
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/external_api/base.py", line 283, in wrapper
    return func(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/external_api/app.py", line 426, in post
    d['blob_uuid'] = a.most_recent_index['blob_uuid']
KeyError: 'blob_uuid'
```
