### ISSUE TITLE
Network interfaces trying to come back from the dead in CI

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#939]
```
Sep  4 04:53:49 jenkins-shakenfist-develop-nightly-165-2 ERROR sf-queues-1630731226.4618623-000[16326] [Exception] Ignored error in sf-queues: ('Invalid state change from %s to %s for object=%s uuid=%s', 'deleted', 'created', 'networkinterface', 'e4ec2da7-7b7a-415a-a6be-d80fdc4c4646')
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/queues.py", line 108, in handle
    instance_start(inst, task.network())
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/queues.py", line 283, in instance_start
    ni.state = dbo.STATE_CREATED
  File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/baseobject.py", line 135, in state
    raise exceptions.InvalidStateException(
shakenfist.exceptions.InvalidStateException: ('Invalid state change from %s to %s for object=%s uuid=%s', 'deleted', 'created', 'networkinterface', 'e4ec2da7-7b7a-415a-a6be-d80fdc4c4646')
```

**Comment by mikalstill** [comment]
Specifically, this instance was requested, and then deleted before the network interface had a chance to be created:

```
Sep  4 04:53:46 jenkins-shakenfist-develop-nightly-165-2 INFO sf-queues[15578] Moved workitem from queue to processing; jobname=1630731226.4618623-000; queuename=sf-2; workitem={'tasks': [QueueTask:PreflightInstanceTask: {'task': 'instance_preflight', 'version': 1, 'instance_uuid': '2c65241f-e384-46be-8114-884e594f5e0b', 'network': [{'address': '192.168.242.96', 'iface_uuid': 'e4ec2da7-7b7a-415a-a6be-d80fdc4c4646', 'macaddress': '02:00:00:a6:d2:71', 'model': 'virtio', 'network_uuid': '806493f2-8ad6-4c82-85a8-bd2f9f1ebafb'}]}, QueueTask:FetchImageTask: {'task': 'image_fetch', 'version': 1, 'url': 'cirros', 'instance_uuid': '2c65241f-e384-46be-8114-884e594f5e0b'}, QueueTask:StartInstanceTask: {'task': 'instance_start', 'version': 1, 'instance_uuid': '2c65241f-e384-46be-8114-884e594f5e0b', 'network': [{'address': '192.168.242.96', 'iface_uuid': 'e4ec2da7-7b7a-415a-a6be-d80fdc4c4646', 'macaddress': '02:00:00:a6:d2:71', 'model': 'virtio', 'network_uuid': '806493f2-8ad6-4c82-85a8-bd2f9f1ebafb'}]}]}

Sep  4 04:53:48 jenkins-shakenfist-develop-nightly-165-1 INFO gunicorn: worker [sf-api][15416] Enqueued workitem; jobname=1630731228.3288953-000; queuename=sf-2; workitem={'tasks': [QueueTask:DeleteInstanceTask: {'task': 'instance_delete', 'version': 1, 'instance_uuid': '2c65241f-e384-46be-8114-884e594f5e0b', 'network': []}]}

Sep  4 04:53:49 jenkins-shakenfist-develop-nightly-165-2 INFO sf-queues-1630731228.3288953-000[16327] Added event; duration=None; fqdn=sf-2; message=None; networkinterface=e4ec2da7-7b7a-415a-a6be-d80fdc4c4646; operation=state changed; phase=initial -> deleted
```

So CI requested this instance, and then deleted it before we had a chance to create it. Specifically I think the issue here is that the instance doesn't enter the `deleted` state before the create starts, so they're running in parallel in different workers.

It seems to me that adding a `delete_wait` state here that the instance enters before the delete heavy lifting happens will alleviate this problem.
