### ISSUE TITLE
Error persisting floating IPs on CI cluster.

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#945]
```
Sep  5 06:19:06 ci-primary INFO sf-net[32258] Reserving address; address=None; ipmanager=floating; networkinterface=0336d738-66c1-4dd6-a7c9-5b81417d28fc
Sep  5 06:19:06 ci-primary sh[31603]: Process sf-queues-fip-reaper:
Sep  5 06:19:06 ci-primary sh[31603]: Traceback (most recent call last):
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
Sep  5 06:19:06 ci-primary sh[31603]:     self.run()
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
Sep  5 06:19:06 ci-primary sh[31603]:     self._target(*self._args, **self._kwargs)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/net.py", line 336, in _reap_leaked_floating_ips
Sep  5 06:19:06 ci-primary sh[31603]:     floating_ipm.persist()
Sep  5 06:19:06 ci-primary sh[31603]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/ipmanager.py", line 64, in persist
Sep  5 06:19:06 ci-primary sh[31603]:     db.persist_ipmanager(self.uuid, d)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/db.py", line 58, in persist_ipmanager
Sep  5 06:19:06 ci-primary sh[31603]:     etcd.put('ipmanager', None, network_uuid, data)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/etcd.py", line 60, in wrapper
Sep  5 06:19:06 ci-primary sh[31603]:     return func(*args, **kwargs)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/etcd.py", line 241, in put
Sep  5 06:19:06 ci-primary sh[31603]:     encoded = json.dumps(data, indent=4, sort_keys=True, cls=JSONEncoderTasks)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
Sep  5 06:19:06 ci-primary sh[31603]:     **kw).encode(obj)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
Sep  5 06:19:06 ci-primary sh[31603]:     chunks = list(chunks)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
Sep  5 06:19:06 ci-primary sh[31603]:     yield from _iterencode_dict(o, _current_indent_level)
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
Sep  5 06:19:06 ci-primary sh[31603]:     yield from chunks
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
Sep  5 06:19:06 ci-primary sh[31603]:     yield from chunks
Sep  5 06:19:06 ci-primary sh[31603]:   File "/usr/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
Sep  5 06:19:06 ci-primary sh[31603]:     items = sorted(dct.items(), key=lambda kv: kv[0])
Sep  5 06:19:06 ci-primary sh[31603]: TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by mikalstill** [comment]
This hasn't been seen for a while.
