### ISSUE TITLE
Floating IP reaper causing a crash

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#950]
```
Sep  6 08:30:07 uat-primary sh[1768]: Process sf-queues-fip-reaper:
Sep  6 08:30:07 uat-primary sh[1768]: Traceback (most recent call last):
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
Sep  6 08:30:07 uat-primary sh[1768]:     self.run()
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
Sep  6 08:30:07 uat-primary sh[1768]:     self._target(*self._args, **self._kwargs)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/net.py", line 336, in _reap_leaked_floating_ips
Sep  6 08:30:07 uat-primary sh[1768]:     floating_ipm.persist()
Sep  6 08:30:07 uat-primary sh[1768]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/ipmanager.py", line 64, in persist
Sep  6 08:30:07 uat-primary sh[1768]:     db.persist_ipmanager(self.uuid, d)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/db.py", line 58, in persist_ipmanager
Sep  6 08:30:07 uat-primary sh[1768]:     etcd.put('ipmanager', None, network_uuid, data)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/etcd.py", line 60, in wrapper
Sep  6 08:30:07 uat-primary sh[1768]:     return func(*args, **kwargs)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/etcd.py", line 241, in put
Sep  6 08:30:07 uat-primary sh[1768]:     encoded = json.dumps(data, indent=4, sort_keys=True, cls=JSONEncoderTasks)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
Sep  6 08:30:07 uat-primary sh[1768]:     **kw).encode(obj)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
Sep  6 08:30:07 uat-primary sh[1768]:     chunks = list(chunks)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
Sep  6 08:30:07 uat-primary sh[1768]:     yield from _iterencode_dict(o, _current_indent_level)
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
Sep  6 08:30:07 uat-primary sh[1768]:     yield from chunks
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
Sep  6 08:30:07 uat-primary sh[1768]:     yield from chunks
Sep  6 08:30:07 uat-primary sh[1768]:   File "/usr/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
Sep  6 08:30:07 uat-primary sh[1768]:     items = sorted(dct.items(), key=lambda kv: kv[0])
Sep  6 08:30:07 uat-primary sh[1768]: TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by mikalstill** [comment]
Oh, this is a typo in a variable name.
