### ISSUE TITLE
Invalid state transition for instances in delete_wait

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#971]
```
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 DEBUG sf-cleaner[11639] Verifying state transition; new state=delete_wait-error; object_type=instance; original state=State({'value': 'delete_wait', 'update_time': 1631528213.3000968}); targets={None: ('initial', 'error'), 'initial': ('preflight', 'delete_wait', 'deleted', 'initial-error'), 'preflight': ('creating', 'delete_wait', 'deleted', 'preflight-error'), 'creating': ('created', 'delete_wait', 'deleted', 'creating-error'), 'created': ('delete_wait', 'deleted', 'created-error'), 'initial-error': 'error', 'preflight-error': 'error', 'creating-error': 'error', 'created-error': 'error', 'error': ('delete_wait', 'deleted', 'error'), 'delete_wait': 'deleted', 'deleted': None}; uuid=5434fd61-b043-4451-9f06-1851efc7c501
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]: Traceback (most recent call last):
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/bin/sf-daemon", line 8, in <module>
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     sys.exit(main())
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/main.py", line 212, in main
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     _audit_daemons()
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/main.py", line 205, in _audit_daemons
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     _start_daemon(d)
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/main.py", line 140, in _start_daemon
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     DAEMON_IMPLEMENTATIONS[d].Monitor(d).run()
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/cleaner.py", line 167, in run
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     self._update_power_states()
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/daemons/cleaner.py", line 129, in _update_power_states
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     inst.state = inst.state.value + '-error'
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:   File "/srv/shakenfist/venv/lib/python3.8/site-packages/shakenfist/baseobject.py", line 145, in state
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]:     raise exceptions.InvalidStateException(
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 sh[11639]: shakenfist.exceptions.InvalidStateException: ('Invalid state change from %s to %s for object=%s uuid=%s', 'delete_wait', 'delete_wait-error', 'instance', '5434fd61-b043-4451-9f06-1851efc7c501')
Sep 13 10:16:55 jenkins-shakenfist-pr-ubuntu-2004-PR-970-1-5 DEBUG sf-queues-1631528214.155399-000[13097] Verifying state transition; new state=deleted; object_type=networkinterface; original state=State({'value': 'created', 'update_time': 1631528189.1220207}); targets={None: ('initial',), 'initial': ('created', 'deleted', 'error'), 'created': ('deleted', 'error'), 'error': ('deleted', 'error'), 'deleted': ()}; uuid=613d157e-a62f-428a-bf4b-884e27a3ea38
```

As seen in https://sfcbr.shakenfist.com/jenkins/job/shakenfist_pr_ubuntu_2004/view/change-requests/job/PR-970/1/execution/node/45/log/?consoleFull

**Comment by mikalstill** [comment]
Fixed. The cleaner now guards on `delete-wait`/`deleted` before appending `-error` (`shakenfist/daemons/cleaner/scheduled_tasks.py:142,216`), and `delete-wait-error` is now a defined valid state, so the InvalidStateException no longer occurs.

*(Triaged with Claude Code; details in CATEGORIZED_BUGS.md on the `bug-cleanup` branch.)*
