### ISSUE TITLE
Traceback in logs

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/shakenfist#988]
```
Sep 17 04:44:04 ci-primary ERROR sf-queues-1631853843.529962-000[10271] [Exception] Ignored error in sf-queues: 'str' object has no attribute 'uuid'
Traceback (most recent call last):
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 139, in handle
    [i.uuid for i in cur_interfaces])
  File "/srv/shakenfist/venv/lib/python3.7/site-packages/shakenfist/daemons/queues.py", line 139, in <listcomp>
    [i.uuid for i in cur_interfaces])
AttributeError: 'str' object has no attribute 'uuid'
```

**Comment by mikalstill** [comment]
Still seeing this.
